psu-libraries/cho

Gemfile
Gemfile.lock
spec/actors/hyrax/actors/image_actor_spec.rb
spec/controllers/hyrax/images_controller_spec.rb
spec/features/create_image_spec.rb
spec/forms/hyrax/image_form_spec.rb
spec/models/collection_spec.rb
spec/models/file_set_spec.rb
spec/models/image_spec.rb
spec/presenters/hyrax/image_presenter_spec.rb

Just adding some really basic tests instead of having all pending tests.

Changing pending tests to really basic tests

---

.gitignore
Gemfile
lib/tasks/testing.rake
public/collection_test.html
spec/actors/hyrax/actors/image_actor_spec.rb
spec/features/create_image_spec.rb

Performs a test where n number of empty works are added to a collection.
The test can be run as a rake task: `bundle exec rake bundle exec rake cho:collection_test[100]`
This creates a collection with 100 items in it. If no number is provided, it defaults to 10.
A report with the most recent test results is available at: `/collection_test`
Example:

Test collection with empty works

---

Gemfile
Gemfile.lock

Very minor change, just adding the `newrelic_rpm` gem to allow for performance monitoring. This will likely help with Adam's pursuit of small-files performance.

Added newrelic gemfile for application monitoring

---

.travis.yml
Capfile
Gemfile
Gemfile.lock
Rakefile
app/controllers/catalog_controller.rb
config/deploy.rb
config/deploy/qa.rb
config/travis/fcrepo_wrapper_test.yml
config/travis/solr_wrapper_test.yml
lib/tasks/resque.rake
tasks/test.rake

Puts New Relic in production only, so we don't run into problems locally, then configures Travis to run our CI build and check for Rubocop violations; lastly, fix the outstanding violations! 🚓

Clean up Gemfile; only use NewRelic in production

---

config/environments/production.rb

Forgot to add resque configuration to the production adapter.

Changing production to use resque

---

Gemfile
Gemfile.lock
spec/factories/metadata_application_profile_field.rb
spec/models/metadata_application_profile_field_spec.rb
spec/rails_helper.rb
spec/support/factory_girl.rb

Adding in factory girl and one factory for the MetadataApplicationProfileField

Adding in factory girl

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
bin/jetty_wait
config/blacklight.yml
spec/features/catalog_spec.rb
spec/rails_helper.rb
spec/support/database_cleaner.rb

Creates a small feature test to ensure Blacklight is working as
expected. Includes some and additions and refactoring of the test suite
to ensure Solr is working in Travis.

Enable feature tests in Blacklight

---

app/models/concerns/with_validation.rb
app/models/metadata_application_profile_field.rb
app/models/validation/none_validator.rb
app/models/validation/validator.rb
app/models/validation/validator_factory.rb
spec/controllers/metadata_application_profile_fields_controller_spec.rb
spec/decorators/csv_metadata_application_field_spec.rb
spec/factories/metadata_application_profile_field.rb
spec/models/metadata_application_profile_field_spec.rb
spec/models/validation/validation_factory_spec.rb
spec/models/validation/validator_spec.rb
spec/presenters/csv_metadata_field_list_presenter_spec.rb
spec/services/metadata_application_profile_csv_importer_spec.rb
spec/support/within_block_is_expected.rb
spec/views/metadata_application_profile_fields/edit.html.erb_spec.rb
spec/views/metadata_application_profile_fields/index.html.erb_spec.rb
spec/views/metadata_application_profile_fields/new.html.erb_spec.rb
spec/views/metadata_application_profile_fields/show.html.erb_spec.rb

Adding the factory for validations to allow for additional validations to be plugged into the system.
The thought would be that each validator could validate a field, and the validationFactory could lookup the validator based on the name.
If we like this pattern I was thinking about using the same one for Auto Complete and Display Transformations.

Added Validation Factory

---

app/cho/controlled_vocabulary/factory.rb
app/cho/display_transformation/factory.rb
app/cho/metadata_application_profile/field_change_set.rb
app/cho/shared/item_factory.rb
app/cho/validation/factory.rb
spec/cho/controlled_vocabulary/factory_spec.rb
spec/cho/display_transformation/factory_spec.rb
spec/cho/metadata_application_profile/field_change_set_spec.rb
spec/cho/shared/item_factory_spec.rb

refs #15 
I believe this is the "final" update to the Base MAP.  That ticket can then be close at the retrospective.

Wiring up factories to change set

---

app/cho/metadata_application_profile/fields_controller.rb
spec/cho/metadata_application_profile/fields_controller_spec.rb

Load the class that is being shown

---

app/assets/stylesheets/blacklight.scss
app/assets/stylesheets/metadata_application_profile_fields.scss
app/blacklight/catalog_controller.rb
app/views/application/_data_dictionary.html.erb
app/views/application/_work_object.html.erb
app/views/data_dictionary/fields/edit.html.erb
app/views/data_dictionary/fields/index.html.erb
app/views/data_dictionary/fields/new.html.erb
app/views/shared/_header_navbar.html.erb
spec/cho/home_page_spec.rb

Also renaming Heading to indicate Data Dictionary
refs #314

Adding menu options for Data Dictionary and New Objects

---

.rubocop_todo.yml
app/cho/data_dictionary/field_change_set.rb
app/cho/data_dictionary/unique_validator.rb
spec/cho/data_dictionary/field_change_set_spec.rb

Adding uniqueness validation for data dictionary field label

---

app/cho/data_dictionary/field.rb
app/cho/data_dictionary/field_change_set.rb
app/cho/data_dictionary/with_index_type.rb
app/views/data_dictionary/fields/_form.html.erb
app/views/data_dictionary/fields/show.html.erb
spec/cho/data_dictionary/field_change_set_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/data_dictionary/with_index_type_spec.rb
spec/factories/field.rb
spec/support/seed_map.rb
spec/views/data_dictionary_fields/edit.html.erb_spec.rb
spec/views/data_dictionary_fields/show.html.erb_spec.rb

adding help text and index type to data dictionary field

---

app/assets/stylesheets/data_dictionary_fields.scss
app/views/data_dictionary/fields/show.html.erb
spec/views/data_dictionary_fields/show.html.erb_spec.rb

changing to a definition list instead of strong with paragraphs

---

app/cho/data_dictionary/fields_controller.rb
app/cho/work_object/deposits_controller.rb

ref #298 
This does not answer the question related to the changeset, but there was some duplicate code I noticed.

Refactoring the controllers to remove duplicate code dealing with changeset

---

.rubocop_todo.yml
app/cho/collection/controller_behaviors.rb
app/cho/data_dictionary/fields_controller.rb
app/cho/work/submissions_controller.rb
app/valkyrie/change_set_persister.rb
spec/cho/data_dictionary/fields_controller_spec.rb
spec/cho/work/submissions/submissions_controller_spec.rb
spec/valkyrie/change_set_persister_spec.rb

@awead here is an idea for encapsulating our desire to capture the exceptions in the persister and always returning a change set
If you like this I can update the other controller to use this pattern too.

Adding a validate and save that can function around a change set

---

pull_request_template.md

Tickets should referenced, and not by using "Fixes" because that
inadvertently moves the ticket into the Done column in Waffle.

Updating PR template

---

tasks/dev.rake

This is helpful when you need to reset the database and the rest of the
related components such as Solr after a rebase or if something just gets
into a weird state.

Rake task to clean dev environment

---

Gemfile.lock

Why was this necessary? Better errors was loading very slowly or not at all. It required an update.
Are there any major changes in this PR that will change the release process? no.

Updating BetterErrors and Binding of Caller

---

app/views/data_dictionary/fields/_form.html.erb
app/views/data_dictionary/fields/index.html.erb
app/views/data_dictionary/fields/show.html.erb
spec/views/data_dictionary_fields/index.html.erb_spec.rb
spec/views/data_dictionary_fields/show.html.erb_spec.rb

Adding core field flag to UI
References ticket: (if any) #404
* Remove Delete and Edit link from data dictionary index page
* Add core field in index and show page

Removing edit and delete links from UI.

---

.rubocop_todo.yml
app/cho/collection/controller_behaviors.rb
app/cho/data_dictionary/fields_controller.rb
app/cho/shared/valkyrie_controller_behaviors.rb
app/cho/work/submissions_controller.rb
spec/cho/shared/valkyrie_controller_behavior_spec.rb

This extracts some of the common Valkyrie behaviors into a module that can be called by the Valkyrie object controllers

Adding Valkyrie Controller Behaviors

---

spec/cho/controlled_vocabulary/base_spec.rb
spec/cho/display_transformation/base_spec.rb
spec/cho/validation/none_spec.rb

Test coverage from some of our base classes was missing, as well as Validation::None.

Adding additional test coverage

---

app/cho/work/submission_change_set.rb

Updating code to only have one error message for missing work type id

---

app/blacklight/catalog_controller.rb
app/blacklight/solr_document.rb
app/cho/data_dictionary/fields_for_solr_document.rb
app/cho/work/submission_indexer.rb
spec/blacklight/solr_document_spec.rb
spec/cho/collection/with_members_spec.rb
spec/cho/work/submissions/indexer_spec.rb

Adds a facet for collection to facet list
References ticket: (if any) #238 
Collection facet before selection
Collection facet after selection 

Adding collection title indexing for Collection facet

---

Gemfile
Gemfile.lock

Improves startup time for the application and test suite.

Installing bootsnap

---

spec/cho/collection/archival_collections/edit_spec.rb
spec/cho/collection/curated_collections/edit_spec.rb
spec/cho/collection/library_collections/edit_spec.rb
spec/cho/work/submissions/edit_spec.rb

Ensures that Solr's records are updated when an edit is performed on a
work or collection.
Fixes #193 

Verify atomic updates

---

app/cho/work/submission.rb
app/cho/work/submission_change_set.rb

Removing some code that we don't need anymore since upgrading to Valkyrie 1.0.

Taking care of some TODOs after upgrading to Valkyrie 1.0

---

Gemfile.lock

Addresses security issue https://nvd.nist.gov/vuln/detail/CVE-2018-11627

Updating Sinatra

---

app/valkyrie/change_set_persister.rb
spec/valkyrie/change_set_persister_spec.rb

Also fixes bug with using just a Valkyrie::ChangeSet
Co-authored-by: Mike Tribone <mtribone@psu.edu>
Fixes: #[issue number, if applicable]

Allowing for multiple unique attributes to update_or_create

---

config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv

Fixes: #514
Corrects the term in the data dictionary.
This was blocking #549.

Rename identified to identifier

---

.solr_wrapper.yml
Gemfile.lock
config/solr_wrapper_test.yml
config/travis/solr_wrapper_test.yml
spec/cho/transaction/operations/import/work_spec.rb

Updates solr wrapper to the latest version to fix some Travis errors.

Updating solr wrapper

---

Gemfile.lock

Updates client to latest version
Bring all clients that we have up to date.
Should not affect application

Update Newrelic client

---

Gemfile.lock

Updates security vulnerabilities in rubyzip and ffi.

Updating rubyzip and ffi to address vulnerabilities

---

app/cho/metrics/repository.rb

This makes the process of resetting the system easier because you don't
remove the entire directory, you only remove its contents.

Clean out directories without removing them

---

spec/cho/work/submissions/new_spec.rb

Ensures that uploading a zip containing multiple filesets, via the GUI,
creates the required files and file sets in the application.

Test uploading a zip with file sets

---

Gemfile
Gemfile.lock
app/cho/data_dictionary/field.rb
app/cho/data_dictionary/fields_for_solr_document.rb
spec/cho/data_dictionary/field_spec.rb

Refactors FieldForSolrDocument to be a little less "floggy."

Refactor FieldsForSolrDocument

---

app/cho/transaction/operations/file/save.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/file_set/extract_text_spec.rb
spec/factories/file_sets.rb
spec/valkyrie/change_set_persister_spec.rb

Perform text extraction when uploading files.
Connected to #652
* failures in extraction are ignored for now (see #700 for follow-up)

Store extracted text on the file set

---

.rubocop.yml
app/blacklight/search_builder.rb
app/cho/work/file_set_indexer.rb
config/initializers/valkyrie.rb
spec/blacklight/catalog_spec.rb
spec/factories/works.rb
spec/fixtures/example_extracted_text.txt

Takes the extracted text from a file set and indexes into Solr and returns any works that contain the extracted text within them.
Connected to #653 
Follow up work identified in #702

Index and search extracted text content

---

app/blacklight/document/csv.rb
app/blacklight/solr_document.rb
spec/blacklight/solr_document_spec.rb

Adds additional lines to the csv when exporting collections and works containing file sets.
Connected to #650

Include file set metadata when exporting collections

---

pull_request_template.md

Adds some description to help us remember what to write for PRs.

Updating the PR template

---

.rubocop_todo.yml
Gemfile.lock
app/cho/agent/change_set.rb
app/cho/agent/csv_agent.rb
app/cho/agent/csv_presenter.rb
app/cho/agent/resource.rb
app/cho/agent/resources_controller.rb
app/cho/data_dictionary/fields_controller.rb
app/cho/shared/valkyrie_controller_behaviors.rb
app/views/agent/resources/_agent.json.jbuilder
app/views/agent/resources/_form.html.erb
app/views/agent/resources/edit.html.erb
app/views/agent/resources/index.csv.erb
app/views/agent/resources/index.html.erb
app/views/agent/resources/index.json.jbuilder
app/views/agent/resources/new.html.erb
app/views/agent/resources/show.html.erb
app/views/agent/resources/show.json.jbuilder
config/routes.rb
spec/cho/agent/agent_spec.rb
spec/cho/agent/controller_spec.rb
spec/cho/agent/routing_spec.rb
spec/cho/shared/valkyrie_controller_behavior_spec.rb
spec/factories/agent.rb

Added model, controller, and views to match with the data dictionary
Added the basics for the rest of the Agent work.
Connected to #730

Adding Agent

---

app/cho/controlled_vocabulary/agents.rb
app/cho/controlled_vocabulary/factory.rb
spec/cho/agent/agent_spec.rb
spec/cho/agent/controller_spec.rb
spec/cho/controlled_vocabulary/agents_spec.rb
spec/cho/controlled_vocabulary/factory_spec.rb
spec/factories/agent.rb

Adds a controlled vocabulary that returns a list of existing agents in the system.
Connected to #732

Controlled vocabulary for existing Agents

---

app/cho/controlled_vocabulary/agents.rb
app/cho/controlled_vocabulary/base.rb
app/cho/controlled_vocabulary/collections.rb
app/cho/controlled_vocabulary/creators.rb
app/cho/controlled_vocabulary/factory.rb
app/cho/controlled_vocabulary/none.rb
app/cho/data_dictionary/creator_field_type.rb
app/cho/data_dictionary/linked_field_type.rb
app/cho/data_dictionary/with_field_type.rb
app/cho/validation/factory.rb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/controlled_vocabulary/creators_spec.rb
spec/cho/controlled_vocabulary/factory_spec.rb
spec/cho/data_dictionary/creator_field_type_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/data_dictionary/linked_field_type_spec.rb
spec/cho/data_dictionary/with_field_type_spec.rb
spec/cho/validation/factory_spec.rb

Adds the linked field and a creator as a kind of linked field.
Connected to #731

Adding in the concept of a linked field type and creator field type

---

app/cho/controlled_vocabulary/creators.rb
spec/cho/controlled_vocabulary/creators_spec.rb

Better error message for unsupported components

Better error message for unsupported components

---

Gemfile
Gemfile.lock
app/cho/data_dictionary/csv_field.rb
app/cho/schema/metadata_field.rb
app/cho/work/with_use_type.rb

Updates Valkyrie to the latest 1.x version.

Updating to Valkyrie 1.4

---

app/cho/metrics/work.rb
config/data_dictionary/data_dictionary_production.csv
config/deploy.rb

These changes were necessary to get MVP 5 deployed to production.
* removing config_update cap task
* updating data dictionary config
* loading mime types dependencies where needed

Preparing for 0.5 release

---

changelog.md

Adding a changelog to document major code changes with each release.
* changelog.md added to project root.

Adding a Changelog

---

app/cho/work/import/csv_dry_run.rb
spec/cho/work/import/csv_dry_run_spec.rb
spec/fixtures/cho_csv.csv

The file saved from Excel includes a BOM character at the front of the file, which we need to handle
refs #815

Adding a test for a file actually exported from Excel

---

Gemfile
Gemfile.lock
app/views/catalog/_document_members.html.erb

Updating to Blacklight 7.0.1

---

app/blacklight/document/csv.rb
spec/blacklight/solr_document_spec.rb

Adds the work_type in for the export of each work
Connected to #817

Adding work type to csv export

---

app/blacklight/document/csv.rb
spec/blacklight/solr_document_spec.rb

Added csv header to the work output
Connected to #752

Adding a header line to work csv output

---

config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv

Updated the index_type of two data dictionary fields. One to make it EDTF, the other to test turning on facets.
Connected to #720
* Changed date_create to have an index_type of date 
* Changed rights_statement to have an index_type of facet

Data dictionary updates to date_created and rights_statement

---

config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv

The recent change to creator validation that was made to test needs to be copied to development and production configs in the data dictionary.

Sync data dictionary configs

---

Gemfile
Gemfile.lock
app/application/application_controller.rb
app/devise/ability.rb
app/views/_user_util_links.html.erb
app/views/agent/resources/index.html.erb
app/views/agent/resources/show.html.erb
app/views/catalog/show.html.erb
spec/application/request_spec.rb
spec/cho/agent/index_spec.rb
spec/cho/agent/show_spec.rb
spec/cho/collection/archival_collections/show_spec.rb
spec/cho/collection/curated_collections/show_spec.rb
spec/cho/collection/library_collections/show_spec.rb
spec/cho/home_page_spec.rb
spec/cho/repository/downloads_controller_spec.rb
spec/devise/ability_spec.rb
spec/factories/users.rb
spec/support/remote_authentication.rb
spec/support/shared/collections.rb

All Penn State users can now access application, but not manage resources.
Connected to #172 
* Create/edit/delete navigation links are hidden where appropriate
* Controllers are locked down, and will 403 if an unauthorized user should visit a route

Opened application to Penn State users

---

app/blacklight/catalog_controller.rb
app/cho/data_dictionary/field.rb
solr/config/schema.xml
spec/blacklight/catalog_spec.rb
spec/cho/data_dictionary/field_spec.rb

There were a number of issues with how the catalog was being searched.
Connected to #839
ref https://github.com/psu-stewardship/chef/pull/856
* Updated the catalog controller to allow for search fields and all fields
* updating the tokenizer in the solr schema to break on all punctuation and underscore

Updating to fix searching

---

app/valkyrie/change_set_persister.rb
spec/valkyrie/change_set_persister_spec.rb

Our change set persister had some methods that weren't being used or
that we don't need anymore.

Cleaning up ChangeSetPersister

---

lib/tasks/index.rake

Utilizes the migration example code form valkyrie to reindex in solr from postgres

Adding a new reindex task

---

spec/cho/collection/archival_collections/edit_spec.rb
spec/cho/collection/archival_collections/new_spec.rb
spec/cho/collection/curated_collections/edit_spec.rb
spec/cho/collection/curated_collections/new_spec.rb
spec/cho/collection/library_collections/edit_spec.rb
spec/cho/collection/library_collections/new_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/import/update_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/archival_collections/new.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/curated_collections/new.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/library_collections/new.html.erb_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

Making tests work if the label for title changes

---

.erb-lint.yml
app/views/agent/import/csv/_dry_run_result.html.erb
app/views/agent/resources/_form.html.erb
app/views/agent/resources/edit.html.erb
app/views/agent/resources/new.html.erb
app/views/agent/resources/show.html.erb
app/views/batch/_document_list.html.erb
app/views/catalog/_show_work_fileset.html.erb
app/views/collection/archival_collections/edit.html.erb
app/views/collection/archival_collections/new.html.erb
app/views/collection/curated_collections/edit.html.erb
app/views/collection/curated_collections/new.html.erb
app/views/collection/library_collections/edit.html.erb
app/views/collection/library_collections/new.html.erb
app/views/layouts/cho.html.erb
app/views/layouts/home.html.erb
app/views/saved_searches/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_form_fields.html.erb
config/locales/cho.yml

Check for, and disallow, hard-coded strings in partials via erb-lint. This ensures our i18n file is always current.
Connected to #507

Enable detection of hard-coded strings in partials

---

config/deploy/prod.rb
config/deploy/stage.rb

Add ability to deploy to stage and master
Connected to APPINT-2757

Added other deploy environments

---

.gitignore
app/assets/stylesheets/cho/header.scss
app/assets/stylesheets/cho/home.scss
app/javascript/packs/form_fields.js
app/views/shared/_form_fields.html.erb

CSS assets were not getting compiled correctly in QA.

Compile image and css elements correctly in production

---

app/cho/metrics/repository.rb
app/cho/transaction/operations/import/extract.rb
config/application.rb
config/initializers/valkyrie.rb
lib/tasks/ingest.rake
spec/cho/transaction/operations/import/extract_spec.rb
spec/cho/work/file_spec.rb
spec/config/application_spec.rb
spec/valkyrie/change_set_persister_spec.rb

Moves directory configuration out of `Metrics::Repository` and into `Cho::Application.config`
Connected to #750

Configure application directories under application.rb

---

config/deploy.rb

Removes unused files and ensure Passenger is restarted at the end of a successful deploy.

Updating Capistrano deployment

---

spec/cho/work/import/create_spec.rb
spec/cho/work/import/update_spec.rb

Changing tests to make them work when creator label is changed

---

app/cho/validation/character_encoding.rb

Fixes the detection of invalid UTF-8 characters in string and text field types.
Connected to #93

Fix detection of invalid UTF-8 characters

---

app/cho/repository/config_file.rb
app/cho/repository/configuration.rb
config/application.yml
config/deploy.rb
lib/tasks/repository.rake
spec/cho/repository/config_file_spec.rb
spec/cho/repository/configuration_spec.rb

Checks for the presence of required settings in specified configuration files, and if the setting is a directory, checks to see if that directory exists on the system.
Connected to #617

Check validity of configuration files during deployment

---

config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv

Updates the date_created property in development and production to be an EDTF date
Connected to #720

Updating dev and prod data dictionary configs for date_created

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb

Updated Capistrano and related gems; fixed linking issues in nfs share; and revised passenger restarts to be like other hosts.
Connected to #APPINT-2783
* bullet-point list of changes, if needed

Cap changes

---

changelog.md

Update changelog for MVP 6 release

---

app/views/_user_profile_links.html.erb

Adds some Bootstrap styles to make the login visible and look like a button. Login button is visually imperceptible with the new header background and look.
* adds Bootstrap class

Login Button

---

solr/config/schema.xml

This will support date range queries used in advanced indexing of EDTF dates.

Adding DateRangeField to Solr schema.xml

---

app/views/shared/_footer.html.erb
config/locales/cho.yml
spec/views/footer.html.erb_spec.rb

Updates the text and truncates the revision number.
Connected to #902 
* Adds CHO to the text
* truncates the revision number output

Footer Text for revisions

---

app/views/work/file_sets/_form.html.erb
app/views/work/file_sets/edit.html.erb

Updates the edit screen for file sets to match Bootstrap style buttons.
Connected to #868 
* adds Bootstrap class for buttons to fileset form and edit

Fileset Buttons to Match other Button in System

---

yarn.lock

This should address the js-yaml security issue, WS-2019-0063.

Updating yarn dependencies

---

.eslintrc.json
app/javascript/controllers/form_controller.js
app/views/collection/base/_form.html.erb
app/views/shared/input_partials/_valkyrie_id.html.erb
app/views/work/submissions/_form.html.erb
package-lock.json
package.json
spec/cho/work/submissions/html5_validation_spec.rb

Using a stimulus controller, we change the default behavior of HTML5 browser validations so that they match the existing behaviors of our other remote validations.

Override HTML5 validations to match our UI pattern

---

.eslintrc.json
app/javascript/controllers/datalist_controller.js
app/views/shared/input_partials/_creator.html.erb
app/views/shared/input_partials/_valkyrie_id.html.erb
spec/cho/work/submissions/multiple_fields_spec.rb
yarn.lock

Adds some additional Javascript interaction that enhances the usability of our datalist selectors. Because we cannot get the label value to display, this adds a span next to the datalist element that shows the label of the selected id.

Display selected values from datalist

---

changelog.md

Updates to the changelog for MVP 7.
Connected to #819

Update changelog for MVP 7
