config/deploy.rb

Temporarily disables BrowseEverything when deploying because of a
support issue in Hyrax.

Disable BrowseEverything, ref #227

---

app/models/concerns/with_field_type.rb
app/models/concerns/with_requirement_designation.rb
app/models/metadata_application_profile_field.rb
db/migrate/20170927135103_create_metadata_application_profile_fields.rb
db/schema.rb
spec/models/field_type_spec.rb
spec/models/metadata_application_profile_field_spec.rb
spec/models/requirement_designation_spec.rb

This is the basic model for storing information about a field in the Base MAP (Metadata Application Profile)
Each field can have the following specified:
* label
* field type
* requirement designation
* controlled vocabulary
* default value
* display name
* display transformation
* multiple
* validation

Adding a model to store a singular field in the Base MAP. refs #15

---

.rubocop.yml

This is to get master passing again. We can make this a default by adding these exemptions to our guides.
I've put in a ticket to discuss if we want to make these changes standard:
https://github.com/psu-stewardship/guides/issues/7.

Exempting view tests from Rubocop length restrictions

---

app/controllers/work_objects_controller.rb
app/views/work_objects/edit.html.erb
spec/features/edit_work_object_spec.rb

Provides the standard Rails delete link to remove a work object from the
system. This will delete it from both Solr and Postgres.

Enable deleting works from the UI

---

app/cho/display_transformation/base.rb
app/cho/display_transformation/error.rb
app/cho/display_transformation/factory.rb
app/cho/display_transformation/none.rb
spec/cho/display_transformation/factory_spec.rb
spec/cho/display_transformation/none_spec.rb

Here is another way to do the Factory.
Not sure if this better or worse than the validation pattern.  The is a single factory for the system, which can have the transformations set on it.

Adding display transformation base

---

app/cho/validation/error.rb
app/cho/validation/validator.rb
spec/cho/display_transformation/none_spec.rb
spec/cho/validation/validator_spec.rb

RSpec was complaining about tests that check for exceptions.
This specifies which errors should be raised when they're supposed to,
and specifies that any error shouldn't be raise when it's not supposed
to.

Avoid false-positives when checking for errors

---

app/cho/controlled_vocabulary/base.rb
app/cho/controlled_vocabulary/error.rb
app/cho/controlled_vocabulary/factory.rb
app/cho/controlled_vocabulary/none.rb
app/cho/metadata_application_profile/field.rb
app/cho/metadata_application_profile/with_vocabularies.rb
spec/cho/controlled_vocabulary/factory_spec.rb
spec/cho/controlled_vocabulary/none_spec.rb
spec/cho/metadata_application_profile/csv_field_spec.rb
spec/cho/metadata_application_profile/csv_importer_spec.rb
spec/cho/metadata_application_profile/csv_presenter_spec.rb
spec/cho/metadata_application_profile/field_spec.rb
spec/cho/metadata_application_profile/fields_controller_spec.rb
spec/factories/field.rb
spec/support/seed_map.rb
spec/views/metadata_application_profile_fields/edit.html.erb_spec.rb
spec/views/metadata_application_profile_fields/index.html.erb_spec.rb
spec/views/metadata_application_profile_fields/show.html.erb_spec.rb

Followed the pattern from the Display Transformation.
If we like this pattern still I think I should also refactor the Validation to use it and possibly extract a generic Factory (As a next step).
Also do we like the separate folders or should this all be under MAP?

Adding controlled vocabulary factory and hooking it into the MAP

---

spec/cho/controlled_vocabulary/none_spec.rb

Ensure that no exception is raised, no matter the specific type. @cam156 sorry, I missed this one on the PR review.

Catch false positives in ControlledVocabulary::None

---

Gemfile
Gemfile.lock
app/cho/metadata_application_profile/fields_controller.rb
spec/cho/metadata_application_profile/fields_controller_spec.rb

When the item is not a change set you get 'ActionView::Template::Error (undefined method 'errors' for #<MetadataApplicationProfile::Field...'

Fixing new to load the form

---

spec/blacklight/catalog_spec.rb
spec/cho/data_dictionary/csv_importer_spec.rb
spec/cho/data_dictionary/fields_controller_spec.rb
spec/cho/work_object/edit_spec.rb
spec/cho/work_object/show_spec.rb
spec/cho/work_object/work_objects_controller_spec.rb
spec/factories/field.rb
spec/factories/work_objects.rb
spec/support/create_for_repository.rb

This uses a new method for creating factory resources that allows us to
use the data mapper pattern. It was copied from Princeton's Figgy
application, which was in turn taking from an issue in FactoryGirl
itself.
FactoryGirl doesn't support persistence via a data mapper pattern, but
the CreateStategyForRepositoryPattern adds the ability to it.

Use FactoryGirl::create_for_repository

---

app/blacklight/catalog_controller.rb
spec/blacklight/catalog_spec.rb

If the user wants a subject or author field they should define a DataDictionary field.  This refrence conflicted with the data dictionary fields

Removing subject and author from catalog controller

---

spec/cho/work_object/objects_controller_spec.rb
spec/support/shared/controllers.rb

This ensures test coverage matches throughout the existing controllers.
We could later make this a shared spec if our controllers have a shared
set of behaviors.

Test for change sets in new actions, ref #319

---

app/cho/shared/common_queries.rb
app/valkyrie/find_using.rb
spec/cho/shared/common_queries_spec.rb
spec/valkyrie/find_using_spec.rb

This takes the existing find_using custom query and extends it to
Valkyrie resources so that we can run ad hoc queries on specific
resource types. Ex:
>  MyClass.find_using(label: 'foo')
=> [MyClass< label: foo>]
I've found myself needing this feature lately as I look for specific work types and fields via their labels. It's been aliased to `where` to give it a more ActiveRecord flavor.

Add find_using as a class method

---

app/blacklight/catalog_controller.rb
app/cho/work/submission_indexer.rb
app/cho/work/submissions_controller.rb
app/cho/work/type.rb
app/views/_user_util_links.html.erb
app/views/application/_work.html.erb
app/views/work/submissions/_nav.html.erb
app/views/work/submissions/new.html.erb
config/initializers/valkyrie.rb
db/seeds.rb
spec/cho/home_page_spec.rb
spec/cho/work/submissions/indexer_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/cho/work/submissions/submissions_controller_spec.rb
spec/cho/work/type_spec.rb
spec/factories/work_types.rb
spec/support/seed_map.rb
spec/views/work_submissions/new.html.erb_spec.rb

This gives us the ability to create new works with pre-defined work types. It does not include the changes required to make the work form display only fields that are available via the work type. I'd like to see that work get separated out into a different ticket, because there may be some outstanding questions, but mainly I wanted to get these changes up and in front of our eyes sooner rather than later.

 Implement set of required work types

---

config/environments/test.rb

This prevents the test suite from failing to start after debugging a
previous run. If you use `byebug` and then forcibly quit the debugger,
there are artifacts leftover in the database that must be removed even
before the application can start up.

Truncate orm_resources table in test

---

app/assets/stylesheets/form.scss
app/views/collection/archival_collections/new.html.erb
app/views/collection/base/_form.html.erb
app/views/collection/curated_collections/new.html.erb
app/views/collection/library_collections/new.html.erb
config/locales/cho.yml
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/archival_collections/new.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/curated_collections/new.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/library_collections/new.html.erb_spec.rb

Fixes #378 and #373 
Running through the interface to swap hard coded text with i18n translations and reworked the collection form for better accessibility. Refactors labels and inputs surrounded with paragraph tags and hard coded breaks with fieldset, legends for organizing form controls into a group for users of accessible technology. Also adds required to title for both the label and the input.
In order to populate text changes in the UI throughout the system easily, we are converting things like titles, labels, buttons, etc. to i18n to have consistent text and easier updates.
Also to target some accessibility errors. We need to have at least one field required, so that librarians can find work in progress in the UI.
Uses the existing i18n for the collections …

Accessible Form Updates and i18n

---

app/valkyrie/find_using.rb
spec/cho/shared/common_queries_spec.rb

Fixes #389.
Becuase all values are enclosed in quotes boolean values can never match the database
1. Bug fix to allow for non string parameters to find_using

Fixing a bug in the common query

---

app/blacklight/catalog_controller.rb
app/cho/collection/type_indexer.rb
config/initializers/valkyrie.rb
config/locales/cho.yml
spec/cho/collection/archival_collections/index_spec.rb
spec/cho/collection/curated_collections/index_spec.rb
spec/cho/collection/library_collections/index_spec.rb
spec/cho/collection/type_indexer_spec.rb
spec/support/matchers/blacklight.rb

Each collection type should have a facet for discovery of additional
collections of the same type. This adds a custom indexer to index the
collection type value into Solr.

Add facet for collection types, ref #374

---

app/cho/data_dictionary/field.rb
app/cho/data_dictionary/field_change_set.rb
db/seeds.rb
spec/cho/data_dictionary/csv_importer_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/schema/metadata_field_spec.rb
spec/factories/field.rb
spec/factories/schema_metadata_field.rb
spec/support/seed_map.rb

refs #322.
Adding a flag to the data dictionary so that core fields can be define in the data dictionary.  I need this for #376 becuase the metadata schema needs to be able to get both core and additional fields from the data dictionary and we need a way to split them up.
1. Adding a Flag to the Data Dictionary
2. Updating Tests to use the flag

Adding core field flag to data dictionary

---

app/cho/data_dictionary/csv_field.rb
spec/cho/data_dictionary/csv_field_spec.rb
spec/cho/data_dictionary/csv_importer_spec.rb
spec/cho/data_dictionary/csv_presenter_spec.rb
spec/cho/data_dictionary/fields_controller_spec.rb

References ticket: #376 
Why was this necessary?   FIelds were added to the data dictionary that were not added to the csv import export process.

Updating csv import export to include new fields

---

app/views/collection/base/_form.html.erb

Swaps `form_with` back to `form_for` to get the label and input ids to match.
Using the new `form_with` does not automatically generate the ID for the input and when I use the same symbol from the `label` element to explicitly set the ID it doesn't prepend the value with the collection type.
#386 
In order to gain greater accessibility with form controls and labels, the  value of the `for` attribute and the `id` need to match.
Swaps `form_with` to be `form_for` instead
No

Quick Accessibility Fix with Form For and ID

---

app/assets/stylesheets/form.scss
app/cho/data_dictionary/fields_for_change_set.rb
app/cho/data_dictionary/with_requirement_designation.rb
app/views/collection/base/_form.html.erb
app/views/work/submissions/_form.html.erb
data_dictionary.csv
spec/cho/data_dictionary/fields_controller_spec.rb
spec/cho/schema/metadata_field_spec.rb

Title is required for the creation of works. Loops through the data dictionary and looks for the fields with the required attribute and adds the additional aria attribute and the span for the required text. Replaces `required_to_publish` with `required` where needed.
#373 
We need at least one identifying field, so that librarians can find unfinished work in a listing of works.
Adds aria required attributes for the title input. Adds the requireddesignation to the data dictionary ruby file and the csv.
Updates style sheet to add bottom margin to all inputs and make the submissions form look for a required designation and add CSS and required attributes to the field. Uses the label for the block, makes the lable titleized, and adds the …

Title is Required for Works

---

app/views/collection/base/_form.html.erb
config/locales/cho.yml
spec/cho/home_page_spec.rb
spec/cho/work/submissions/new_spec.rb

Swaps out hard coded text for the interface with translations in the cho yml.
#378 
Hard coded text in the interface is hard to change in multiple places. Much better to write it once and reference it everywhere.
Adds translation for the navigation links and the collection form until it is changed to pull from the data dictionary. Updates the tests to use work instead of submission.

Adds Additional translations for the Interface

---

spec/application/application_cable/channel_spec.rb
spec/application/application_cable/connection_spec.rb
spec/application/application_job_spec.rb
spec/application/application_mailer_spec.rb

Why was this necessary? Coveralls had some 0% tests for some of our Rails application classes.

Add simple test coverage for rails application classes

---

app/assets/stylesheets/blacklight.scss
app/assets/stylesheets/form.scss
app/blacklight/catalog_controller.rb
app/blacklight/layout_helper_behavior.rb
app/views/catalog/_search_results.html.erb
app/views/catalog/index.html.erb
app/views/catalog/show.html.erb
app/views/data_dictionary/fields/index.html.erb
app/views/layouts/blacklight.html.erb
app/views/saved_searches/index.html.erb
app/views/search_history/index.html.erb
app/views/work/submissions/_form.html.erb
config/locales/blacklight.en.yml
spec/blacklight/search_history_spec.rb

Refactors the default view so that the main h1 isn't hidden and isn't repeating the name of the application. Refactors the headings and layout for the search results page, so that we have a good document outline and that the content comes before the facets in the code.
Fixes insuficient color contrast and overrides the layout helper for column sizes.
Adds label for the file upload button and a table header for the data dictionary.
Replaces the search history table with an unorderd list.
Aligns HTML for search history and saved searches.
Rubocop fixes.
Fixes the layout helper from blacklight so that the show page doesn't have the pull class to keep the tools column on the right.
Are there any major changes in this PR that will change the …

WAVE Report Errors and Warnings

---

app/assets/stylesheets/blacklight.scss

Adds the outline to the Bootstrap dropdown when tabbing through the interface.
References ticket: (if any) #305 
A visual focus indicator is import for those individuals who navigate through the interface using a keyboard.
Updates the blacklight style sheet to target a specific class of a dropdown

Tab test Change

---

app/views/collection/archival_collections/new.html.erb
app/views/collection/curated_collections/new.html.erb
app/views/collection/library_collections/new.html.erb
app/views/data_dictionary/fields/edit.html.erb
app/views/data_dictionary/fields/new.html.erb
app/views/data_dictionary/fields/show.html.erb
app/views/work/submissions/edit.html.erb
app/views/work/submissions/new.html.erb
config/locales/cho.yml
spec/cho/collection/archival_collections/show_spec.rb
spec/cho/collection/curated_collections/show_spec.rb
spec/cho/collection/library_collections/show_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/cho/work/submissions/new_spec.rb

Removes the inconsistently working back link from the interface.
References ticket: (if any) #414 
The back link wasn't working consistently and there are other ways in the interface to get around
Deletes the back link from the works and collection views 

Remove the Back Link from Forms

---

app/assets/stylesheets/blacklight.scss
app/views/catalog/_document_members.html.erb
app/views/layouts/blacklight.html.erb
app/views/shared/_header_navbar.html.erb
spec/cho/home_page_spec.rb

Adds a column scope to the header in the table for accessibility, skip to content link for keyboard users, removes an extra ARIA landmark, and switches the main-content div to an HTML5 main element.
References ticket: (if any) #305 
Makes it better for screen reader and keyboard users.
Adds the column attribute to the table headers. Removes extra landmark role. Adds skip link to main content. 

Accessibility for Tables and Screen Reader Adjustments

---

config/deploy.rb
config/deploy/qa.rb

The initial deploy configuration was copied over from Scholarsphere. Most of this doesn't apply to our current setup, so we're removing it in favor of a simpler configuration.
Are there any major changes in this PR that will change the release process? Yes
There are new directories in the server's shared Capistrano directory. These directories must exist when the application is deployed.

Updating Capistrano deploy

---

README.md

Remove development setup instructions from the README. They're in the wiki now.

Moving README information into the wiki

---

app/cho/shared/common_queries.rb
spec/cho/shared/common_queries_spec.rb

Returns true if the record exists, false if it does not, and raises an error if it exists but as a different class than the one being queried.
Why was this necessary? This would be helpful in many different contexts.

Add exists? method to CommonQueries

---

config/valkyrie.yml

Matches up with the configured storage adapter
References ticket: #359
Why was this necessary?  Is causing a null pointer exception when the storage adapter is used, since fedora is not configured.

Changing production to disk

---

Gemfile.lock

Update the loofah gem to address security vulnerability.

CVE-2018-8048 - Loofah XSS Vulnerability

---

app/assets/stylesheets/application.css
app/assets/stylesheets/cho.scss
app/assets/stylesheets/cho/blacklight.scss
app/assets/stylesheets/cho/data_dictionary_fields.scss
app/assets/stylesheets/cho/form.scss
app/assets/stylesheets/cho/scaffolds.scss
app/assets/stylesheets/cho/variables.scss

Adds a cho.scss file and imports the partials. Updates css for syntax errors.
Moves the CHO-specific and venodr overrides into a CHO folder and imports those CSS files into the application.css. Fixes all issues reported by the SCSS Linter.
Updates CSS and SCSS styles according to current best practices.
Moved SCSS files into a CHO folder.

SCSS Linting for CHO

---

.rspec
.travis.yml
config/travis/solr_wrapper_test.yml
travis/test.sh

Configures Travis to use stage builds with a separate check for linters, using Niftany, to run first. The second stage is the rspec test.
This also corrects an error with the solr version of the Travis configuration.
Allows Travis to check to linter errors prior to running the test suite.

Configuring Travis for stage build with Niftany

---

app/cho/work/submission.rb
app/cho/work/submission_change_set.rb
app/cho/work/submission_indexer.rb
app/cho/work/submissions_controller.rb
app/views/work/submissions/_form.html.erb
app/views/work/submissions/_nav.html.erb
app/views/work/submissions/new.html.erb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/cho/work/submissions/indexer_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/cho/work/submissions/show_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/cho/work/submissions/submissions_controller_spec.rb
spec/factories/works.rb
spec/views/work_submissions/edit.html.erb_spec.rb
spec/views/work_submissions/new.html.erb_spec.rb

Co-authored-by: Michael Tribone mtribone@psu.edu
Changed the work_type attribute for Work::Submission and
Work::SubmissionChangeSet to work_type_id, using the Valkyrie ID instead
of just a string.
Fixes: #419
We needed to be more consistent about attributes names and remove confusion over object properties and id properties.

Change work_type to work_type_id

---

app/cho/collection/change_set_behaviors.rb
app/cho/collection/common_fields.rb
app/cho/collection/controller_behaviors.rb
app/cho/data_dictionary/fields_for_object.rb
app/views/collection/archival_collections/edit.html.erb
app/views/collection/base/_form.html.erb
app/views/collection/curated_collections/edit.html.erb
app/views/collection/library_collections/edit.html.erb
app/views/shared/_form_fields.html.erb
app/views/work/submissions/_form.html.erb
config/data_dictionary/schema_fields.yml
db/seeds.rb
spec/cho/collection/archival_collections/archival_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/collection/common_fields_spec.rb
spec/cho/collection/curated_collections/curated_spec.rb
spec/cho/collection/library_collections/library_spec.rb
spec/support/shared/collections.rb
spec/support/shared/controllers.rb
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/archival_collections/new.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/curated_collections/new.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/library_collections/new.html.erb_spec.rb

Allows us to define the same set of core fields for collections that are
used for works. Additional configuration can later be added to expand
fields on collections and vary them by the collection class.
Fixes #407 
Makes the process for defining fields on works and collections the same.

Use a metadata schema for collections

---

app/cho/work/import/csv_controller.rb
app/cho/work/import/csv_file.rb
app/cho/work/import/csv_importer.rb
app/cho/work/import/csv_reader.rb
app/cho/work/import/work_hash_validator.rb
app/views/work/import/csv/dry_run_results.html.erb
app/views/work/import/csv/import_failure.html.erb
app/views/work/import/csv/import_success.html.erb
app/views/work/import/csv/new.html.erb
config/locales/cho.yml
config/routes.rb
spec/cho/work/import/csv_controller_spec.rb
spec/cho/work/import/csv_dry_run_spec.rb
spec/cho/work/import/csv_importer_spec.rb
spec/fixtures/hello_world2.txt
spec/fixtures/hello_world3.txt

Creates works by importing a csv file in the UI, running a dry run, and import.
Running this brings up some issues.
1. How are we getting the files attached to the work?
1. Should this really be a UI element based on question 1?
1. When the same file gets uploaded twice the upload process errors (files are stored on disk with their original file name)
References ticket: (if any) #238 
* Adds a Importer for the CSV Dry Run Results
* Adds files to the DRY Run
* Adds UI elements for running the entire process (very basic)

Full loop from file to repo

---

app/blacklight/document/csv.rb
app/blacklight/solr_document.rb
app/cho/data_dictionary/field.rb
app/cho/data_dictionary/fields_for_solr_document.rb
app/cho/shared/csv_parsing.rb
app/cho/work/import/csv_reader.rb
app/cho/work/submission_indexer.rb
config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/work/import/csv_reader_spec.rb

* Adds .csv format to show for work and collection
* Adds method name to field
* Changed field methods defined on SolrDocument to not conflict with existing methods. resource field vs resource method existing on solr document
* Changes indexer to use new method name
References ticket: (if any) refs #17
Why was this necessary? Adding export as requested by users

Adding csv export 

---

Gemfile
Gemfile.lock
spec/factories/archival_collections.rb
spec/factories/curated_collections.rb
spec/factories/field.rb
spec/factories/library_collections.rb
spec/factories/schema_metadata.rb
spec/factories/schema_metadata_field.rb
spec/factories/users.rb
spec/factories/work_file.rb
spec/factories/work_types.rb
spec/factories/works.rb
spec/support/create_for_repository.rb
spec/support/factory_girl.rb

Replaces the FactoryGirl gem with FactoryBot. Same functionality, just a
better name.
Fixes: #400 
Why was this necessary? The old gem name was problematic. The new gem name is less controversial.

Upgrade to FactoryBot

---

app/cho/collection/common_fields.rb
app/cho/work/submission_change_set.rb
spec/cho/collection/common_fields_spec.rb

refs #415
.member is being depricated

Changing Set.member to Set.of

---

app/cho/work/submission.rb
spec/cho/work/submissions/submission_spec.rb

This changes the type of the values in the list to ids.
This does not really enforce that an id must be used, since Valkyrie::Types:ID take any value in it's constructor and does a to_s on it.
In addition we needed to add a default to the definition becuase of a bug in Dry::Types.  Valkyrie 1.0 works around this bug, so upgrading will allow us to remove our default.
References ticket: (if any) #415
Why was this necessary? For consistency and documentation to enforce that member_of_collections_ids will actually be Ids.

Changing Submission to define it should have a Set of Ids for member_of_collections_id

---

app/cho/collection/controller_behaviors.rb
app/cho/work/submissions_controller.rb
spec/cho/work/submissions/submissions_controller_spec.rb
spec/support/shared/controllers.rb

This makes sure that when there is an error with the model you will see the changes in the form and not just an empty form or the work's\collection's original values.
References ticket: (if any)  #425
Why was this necessary?  The form was coming back either empty or with the original values, not the values the user had typed in before the error.
* Sync is now called on error to make sure the change set is showing the values entered by the user

Adding sync to change set so model is populated for work & Collectin edit and new

---

app/cho/collection/change_set_behaviors.rb
app/cho/schema/input_field.rb
app/cho/work/submission_change_set.rb
app/views/shared/_form_fields.html.erb
config/data_dictionary/data_dictionary_test.csv
spec/cho/collection/archival_collections/edit_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/collection/curated_collections/edit_spec.rb
spec/cho/collection/library_collections/edit_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/archival_collections/new.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/curated_collections/new.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/library_collections/new.html.erb_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

Renders a text area when the data dictionary field type is 'text.' By
default, everything else is still a text input.
Fixes: #475 
Why was this necessary? The description field was not rendered as a text area.

Enforce the text type in data dictionary for description

---

Gemfile
Gemfile.lock

Re-enable New Relic. The error with rake tasks seems to have resolved itself.
Fixes: #225 

Re-enabling New Relic in production

---

app/cho/metrics/collection.rb

Capture statistics from New Relic when we run our benchmark metrics.
New Relic was not capturing any data when benchmarks were run. Adding
the tracer to the process solves the issue.
This was based on documentation from New Relic:
https://docs.newrelic.com/docs/agents/ruby-agent/background-jobs/monitor-ruby-background-processes

Adding New Relic tracer to Metrics::Collection

---

app/cho/metrics/repository.rb
config/application.yml
lib/tasks/benchmark.rake
spec/cho/metrics/repository_spec.rb
tasks/dev.rake

Cleaning out the repository and running benchmarks is a common task for specific environments. However, it should only be allowed in specific ones, for example, only in QA or local and not in production.
This makes running benchmarks and resetting the QA environment an easier process.
Are there any major changes in this PR that will change the release process? Yes, we need to add a new key to the server's application.yml file.

Allow repository resets in selected service environments

---

Gemfile
Gemfile.lock
app/cho/work/submission.rb
app/valkyrie/indexing_adapter.rb
app/valkyrie/memory/singular_delete_tracking_buffer.rb
app/valkyrie/memory/singular_metadata_adapter.rb
app/valkyrie/memory/singular_persister.rb
app/valkyrie/postgres/singular_metadata_adapter.rb
app/valkyrie/postgres/singular_persister.rb
app/valkyrie/solr/singular_metadata_adapter.rb
app/valkyrie/solr/singular_persister.rb
app/valkyrie/solr/singular_repository.rb
config/initializers/valkyrie.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/schema/metadata_field_spec.rb
spec/cho/schema/metadata_spec.rb
spec/support/factory_girl.rb
spec/support/shared/collections.rb
spec/valkyrie/indexing_adapter_spec.rb
spec/valkyrie/memory/singular_adapter_spec.rb
spec/valkyrie/memory/singular_delete_tracking_buffer_spec.rb
spec/valkyrie/memory/singular_persister_spec.rb
spec/valkyrie/postgres/singular_adapter_spec.rb
spec/valkyrie/postgres/singular_persister_spec.rb
spec/valkyrie/solr/singular_adapter_spec.rb
spec/valkyrie/solr/singular_persister_spec.rb

I was walking down the path of making everything plural and then I got to the part where we were outputting our data and realized it really needed to be singular there.  That meant we would need to translate from plural to singular.  That got me thinking why translate at the outside of the system.  Why not do the translation at the persistence layer?
I brought that thought to refactoring and we took it a step further.  What would happen if we just allowed Singular to  work.  The result is a set of persister that do not check for multiple.
This made almost every test pass, except for the few that relied on the new parameter new_record.
I'm not entirely positive this is what we want to do, or if we want to create an "Saveable" object that translates any singular property into multiple …

Creating persisters that allow for singular, since it works for us

---

app/cho/work/submission_change_set.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/delete_spec.rb
spec/cho/work/submissions/submissions_controller_spec.rb
spec/factories/archival_collections.rb
spec/factories/works.rb
spec/valkyrie/change_set_persister_spec.rb

A submission change change with an empty array of member collections will still be valid. This seems wrong. If works are supposed to always be in a collection, then the submission change set should not be valid if there is not at least one id in the array of member collections.
This should prevent the occurrence of works without a parent collection.

Submission change sets should require a collection

---

.solr_wrapper.yml
Gemfile
Gemfile.lock
config/solr_wrapper_test.yml
config/travis/solr_wrapper_test.yml

Update solr wrapper to latest in master so we can use a different mirror.
Travis appears to be timing out when downloading solr, indicating the url isn't responding.

Updating solr_wrapper to use different mirror

---

app/blacklight/catalog_controller.rb
app/cho/work/import/csv_controller.rb
app/cho/work/import/csv_dry_run_results_presenter.rb
app/views/application/_csv_import.erb
app/views/work/import/csv/_dry_run_error_list.html.erb
app/views/work/import/csv/_dry_run_result.html.erb
app/views/work/import/csv/dry_run_results.html.erb
app/views/work/import/csv/import_success.html.erb
app/views/work/import/csv/new.html.erb
config/locales/cho.yml
spec/cho/work/import/csv_controller_spec.rb
spec/cho/work/import/csv_dry_run_results_presenter_spec.rb
spec/cho/work/import/import_spec.rb

Improve and implement the UI workflow for importing a CSV file based on a wireframe.
References ticket: (if any) #236 #235 
Admin users would like to import works via a CSV file because it is easier and matches their workflow when wanting to import many things.
Putting dry run results into a table with status messages for good stuff and works with errors. Created a partial for the errors to loop through each error message for the import.
Added some Bootstrap styles and moved the caption text into a header element. Fixes rubocop errors, makes the form inline, moves the cancel into the form, adds header to CSV Import start page.
Added new nav action in the catalog controller for CSV import, added partial for the link, and added i18n for the text.
Clean up CSV import …

Implement the User Interface for CSV Import

---

app/cho/data_dictionary/csv_importer.rb
app/cho/schema/configuration.rb
app/cho/schema/metadata_core_fields.rb
app/cho/schema/work_type_configuration.rb
app/valkyrie/change_set_persister.rb
config/data_dictionary/schema_fields.yml
db/seeds.rb
spec/cho/data_dictionary/csv_importer_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/schema/metadata_core_fields_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/valkyrie/change_set_persister_spec.rb

This allows it to be tested
This is a precursor to adding more functionality to the Schema configuration to allow for each schema to override data dictionary field attribute values
refs #437

Moving code out of seed into appropriate classes

---

app/cho/collection/archival.rb
app/cho/collection/curated.rb
app/cho/collection/library.rb
app/cho/data_dictionary/field.rb
app/cho/schema/metadata.rb
app/cho/schema/metadata_field.rb
app/cho/work/file.rb
app/cho/work/submission.rb
app/cho/work/type.rb

Comments explain which persisters are used for a resource, such as
whether or not it is index in Solr or not.
Fixes: #402

Adding documentation to our resources.

---

app/cho/schema/metadata_field.rb
app/cho/schema/work_type_configuration.rb
config/data_dictionary/schema_fields.yml
spec/cho/schema/configuration_spec.rb
spec/cho/schema/metadata_field_spec.rb
spec/cho/schema/work_type_configuration_spec.rb

refs #437
References ticket: (if any) refs #437
Why was this necessary?  Allows for schema values to override the data dictionary fields.

Adding schema config merge to initialize_from_data_dictionary_field

---

app/valkyrie/find_using.rb
spec/cho/shared/common_queries_spec.rb
spec/valkyrie/find_using_spec.rb

References ticket: (if any) #437
Why was this necessary? Schema::Fields are going to be unique by their WorkType and Label not just their label.  Allowing for multiple fields will let us find them
Allow find_using to accept multiple terms

Allowing find by multiple terms

---

app/assets/stylesheets/cho.scss
app/assets/stylesheets/cho/blacklight.scss
app/assets/stylesheets/cho/facets.scss
app/assets/stylesheets/cho/form.scss
app/assets/stylesheets/cho/scaffolds.scss
app/assets/stylesheets/cho/variables.scss
app/views/_user_util_links.html.erb
app/views/batch/_document_list.html.erb
app/views/search_history/index.html.erb
app/views/work/import/csv/create.html.erb
app/views/work/import/csv/update.html.erb
spec/blacklight/search_history_spec.rb

Co-authored-by: Adam Wead <amsterdamos@gmail.com>
Update styles to user util links for the link reorganization. Removes empty searches from search history. Improves accessibility of the delete checkboxes on the select resources page, Adds label for form elements on the work create and update page. Updates CSS for contrast and accessibility errors. 
References ticket: (if any) #306
WAVE accessibility toolbar reported errors and warnings throughout the interface.
Improved the links in the toolbar and the search history showing blank searches. Lots of color contrast changes and some Bootstrap overrides until Bootstrap 4 tickets for accessibility are closed.

MVP 2 Accessibility Check-up

---

app/cho/schema/configuration.rb
app/cho/work/file_set.rb
app/cho/work/file_set_change_set.rb
app/cho/work/submission_change_set.rb
app/cho/work/with_valid_members.rb
config/data_dictionary/schema_fields.yml
spec/cho/schema/configuration_spec.rb
spec/cho/work/file_set_change_set_spec.rb
spec/cho/work/file_set_spec.rb

Fixes #550 
Provides a resource to group multiple Work::File objects together. This is analogous to the FileSet class in the Hydra works extension to PCDM. One original file is grouped together with multiple derivative files, including auto and manually generated derivatives, and extracted information such as text or other technical metadata.

FileSet resource class for grouping files

---

app/cho/vocab/file_use.rb
app/cho/work/file.rb
app/cho/work/file_change_set.rb
app/cho/work/use_type_validator.rb
app/cho/work/with_use_type.rb
app/valkyrie/change_set_persister.rb
spec/cho/work/file_change_set_spec.rb
spec/cho/work/file_spec.rb
spec/cho/work/with_use_type_spec.rb
spec/factories/work_file.rb
spec/valkyrie/change_set_persister_spec.rb

Connects to #512
This doesn't define a schema for Work::File resources, but instead provides an internal controlled vocabulary for what use types we can assign to the file.
I'm totally satisfied with it. I've provided a Work::FileChangeSet to provided better feedback for errors with file, but we're not using it yet. I imagine it will be needed for later tickets when reporting errors with file sets during the bag import process.
Also, there is duplication of validation between the file resource and its change set. This is so the existing change set persister can save files correctly, with a default preservation use type. This will also need to change later as we will want to pass specific use types to the persister.
Are there any major changes in this PR that will change the release …

Add use type URIs to Work::File

---

app/cho/schema/input_field.rb
app/cho/schema/metadata_core_fields.rb
app/views/shared/_form_fields.html.erb
config/data_dictionary/data_dictionary_test.csv
spec/cho/data_dictionary/fields_controller_spec.rb
spec/cho/schema/metadata_field_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

refs #437
Why was this necessary?  The display name was not being used for a label.
Use the display name on the edit form.
Update the test data dictionary to have  a display name for title to test this further.

Allowing the display name to be show on the edit page or work and collection

---

app/blacklight/catalog_helper.rb
app/blacklight/solr_document.rb
app/cho/schema/metadata.rb
spec/blacklight/solr_document_spec.rb
spec/cho/schema/metadata_spec.rb
spec/cho/work/submissions/index_spec.rb
spec/cho/work/submissions/show_spec.rb
spec/support/matchers/blacklight.rb

Fixed up custom matchers to truely match
Added override of CatalogHelper to change label based on document schema
updated solr document to lookup schema
updated Schma::Metadata to find field by label in either core or regular fields
Fixes: #437 

Adding display name to index and show

---

Gemfile
Gemfile.lock
app/cho/transaction/file/create.rb
app/cho/transaction/file/delete.rb
app/cho/transaction/file/update.rb
app/cho/transaction/operations/container.rb
app/cho/transaction/operations/file/delete.rb
app/cho/transaction/operations/file/save.rb
app/cho/transaction/operations/file/validate.rb
app/valkyrie/change_set_persister.rb
config/data_dictionary/schema_fields.yml
spec/cho/transaction/file/create_spec.rb
spec/cho/transaction/file/delete_spec.rb
spec/cho/transaction/file/update_spec.rb
spec/cho/transaction/operations/file/delete_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/file/validate_spec.rb

@awead  @mtribone and I have been looking at how dry-transactions could fit into the system.
We included the gem and added classes (no implementation), and configuration for how it might work.  Let us know if this seems reasonable and we will try to hook it into the file creation process in the existing system.
The very basic idea is that you have Transactions in the system that you can choose from in your configuration for what you want to occur when a file is created, updated, and deleted.  Each transaction is a dry-transaction, which is a series of operations.  Operations cab be reused between Transactions and we could have different Transactions for different work types.
Adds a basic set of dry-transactions operations for a file.
Are there any major changes in this PR that will change …

Adding in dry-transactions for creating updating and deleting a file

---

app/blacklight/catalog_controller.rb
app/cho/data_dictionary/field.rb
app/cho/schema/work_type_configuration.rb
config/data_dictionary/schema_fields.yml
spec/cho/schema/configuration_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/support/seed_map.rb
spec/views/work_submissions/edit.html.erb_spec.rb

add sort to catalog data dictionary display
add sort to core fields
make sure the order index does not get overriden
Fixes: #437
Allows core field to be overridden without killing the order index.  Not this does not update the order on the show and index views, but does update the order on the edit and new forms.

Allow core fields to be overridden

---

Gemfile.lock

Patches security vulnerability in the sprockets gem outlined in https://nvd.nist.gov/vuln/detail/CVE-2018-3760.

Updating Sprockets to address CVE-2018-3760

---

app/cho/transaction/operations/container.rb
app/cho/transaction/operations/shared/create_change_set.rb
app/cho/transaction/operations/shared/save.rb
app/cho/transaction/operations/shared/validate.rb
app/cho/transaction/shared/save_with_change_set.rb
app/cho/transaction/shared/save_with_resource.rb
app/valkyrie/change_set_persister.rb
spec/cho/transaction/operations/shared/create_changeset_spec.rb
spec/cho/transaction/operations/shared/save_spec.rb
spec/cho/transaction/operations/shared/validate_spec.rb
spec/valkyrie/change_set_persister_spec.rb

These transactions can be used for any object
Modified change_set_persister to utilize the new transactions
Why was this necessary?  Utilizing the new pattern
1. Created new shared operations: CreateChangeSet, Validate, and Save
1.  Created a Save transaction for any object
1. Updated ChangeSetPersister to use the new Transaction

Adding transactions for creating, validating, and creating change sets

---

app/blacklight/solr_document.rb
app/cho/transaction/operations/file/save.rb
app/cho/work/submission.rb
app/cho/work/submission_change_set.rb
app/valkyrie/change_set_persister.rb
app/views/catalog/_file_sets.html.erb
app/views/catalog/_show_work_submission.html.erb
spec/blacklight/solr_document_spec.rb
spec/cho/metrics/work_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/factories/file_sets.rb
spec/valkyrie/change_set_persister_spec.rb

Takes the existing single-file upload process done in the GUI and adds
the file set resource as the intermediary between the work and file.
Single files that are uploaded via the GUI are now stored in a file set that is attached to the work resource.

Implement file sets with GUI upload

---

app/blacklight/catalog_controller.rb

Fixes: #536 
The autocomplete has a few accessibility issues and it also stores each state of the autocomplete in the search history, so we are "removing" the autocomplete by commenting it out in the catalog controller.
Are there any major changes in this PR that will change the release process? Nope

Comments out the autocomplete feature

---

app/views/work/submissions/_form.html.erb
config/locales/cho.yml
spec/views/work_submissions/edit.html.erb_spec.rb
spec/views/work_submissions/new.html.erb_spec.rb

Removes the screen reader only class and exposes the i18n label to have the file selection elements below the collection datalist.
Fixes: #590 
Alignment of the file selection form elements was too close to the collection member datalist and cuased user confusion.

File Selection Button Alignment

---

app/cho/import/bag.rb
spec/cho/import/bag_spec.rb

Raise an error when attempting to validate a bag that doesn't exist,
otherwise, the default behavior of the BagIt gem is to create an empty
bag using that path.
Connects #549

Guard against bags that don't exist

---

app/cho/work/submission.rb
app/cho/work/submission_change_set.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/submission_spec.rb

Fixes #597
Allows us to track which batch, and therefore which zip file, created a work.

Persist batch id on the work

---

app/cho/import/work.rb
spec/cho/import/work_spec.rb

Connects to #549 
Allows one to access the path to a work within a bag, and refer to its identifier, which is the name of its directory.
Why was the necessary?
In order to import works in a bag, we'll need to know where on the file system the work is, and if the work's identifier matches the one in the CSV file.

Add path and identifier to import work

---

app/cho/work/import/csv_dry_run.rb
app/cho/work/submission_change_set.rb
config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/schema/metadata_core_fields_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/cho/work/import/csv_dry_run_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/support/import_factory/zip.rb

Connects to #549 
Attaches the import works found in the bag to each result of the `CsvDryRun`. Bags are extracted and verified using a transaction, which is also available on the `CsvDryRun` object.
In order to import new works from a csv file and a bag, we need to attach and verify the works found in the bag with the works that are specified in the csv file.
* adds `identifier` to the test data dictionary so we can set it to the value specified in the csv
* includes an `ImportFactory::Zip` testing support class for creating zip files from bags created using `ImportFactory::Bag`
* defines a special `import_work` accessor on `SubmissionChangeSet` which is set by the csv dry run so we can assign an `Import::Work` object to the change set, but not persist or use it …

Adding bag and import work to CsvDryRun

---

app/cho/import/file.rb
app/cho/import/file_set.rb
app/cho/transaction/operations/container.rb
app/cho/transaction/operations/import/work.rb
app/cho/transaction/shared/save_with_change_set.rb
spec/cho/import/file_set_spec.rb
spec/cho/import/file_spec.rb
spec/cho/transaction/operations/import/work_spec.rb
spec/cho/transaction/shared/save_with_change_set_spec.rb
spec/cho/work/import/create_spec.rb

Connects to #549 
Creates a transaction that imports a work from a bag and attaches it to a new work during the csv import process.
This enables us to import works from a bag and a csv file.
* new convenience methods on Import::File and Import::FileSet to better enable import
* Import::Work operation to add file sets and files from a bag to a new work
* updated feature test that uses bags to import works via csv

Operation to import files from a bag

---

spec/cho/import/work_spec.rb
spec/support/import_factory/work.rb

The method on ImportFactory::Work was incorrectly named. This renames it to the more consistent `create`.

Rename new_create to create

---

app/cho/work/import/csv_dry_run.rb
app/cho/work/import/work_hash_validator.rb
spec/cho/work/import/csv_controller_spec.rb
spec/cho/work/import/csv_dry_run_spec.rb
spec/cho/work/import/work_hash_validator_spec.rb

Fixes #549 
Removes the ability to upload single files in a CSV.
Single-file upload is no longer supported in a CSV, only bag upload.

Remove single file upload from CSV import

---

Gemfile
Gemfile.lock
app/cho/transaction/operations/shared/save.rb
app/cho/work/submission.rb
app/cho/work/submission_change_set.rb
app/valkyrie/find_using.rb
app/valkyrie/postgres/singular_metadata_adapter.rb
app/views/work/submissions/_form.html.erb
config/locales/cho.yml
db/migrate/20180810135054_create_path_gin_index.valkyrie_engine.rb
db/migrate/20180810135055_create_internal_resource_index.valkyrie_engine.rb
db/migrate/20180810135056_create_updated_at_index.valkyrie_engine.rb
db/migrate/20180810135057_add_optimistic_locking_to_orm_resources.valkyrie_engine.rb
db/schema.rb

Updates Valkyrie to 1.2.0.rc1 and enables optimistic locking on Work::Submission resources.
Postgres migration is required to add the new columns for the optimistic lock token.

Update Valkyrie and enable optimistic locking

---

app/cho/import/file.rb
app/cho/work/import/csv_dry_run_results_presenter.rb
config/locales/activemodel_errors.yml
spec/cho/import/bag_spec.rb
spec/cho/import/work_spec.rb
spec/cho/transaction/operations/import/validate_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/import/csv_dry_run_results_presenter_spec.rb

Overrides ActiveModel::Errors defaults to create custom error messages
using locale files.

Nicer validation error messages

---

Gemfile
Gemfile.lock

Updates CHO to the 1.2.0 release of Valkyrie which supports optimistic locking and single-valued attributes.

Updating Valkyrie to 1.2.0

---

app/cho/data_dictionary/fields_for_object.rb

Uses the latest features from Valkyrie to ensure all properties that are defined dynamically via DataDictionary are ordered by default.

Enable ordering on all data dictionary properties

---

Gemfile
Gemfile.lock
app/cho/data_dictionary/csv_importer.rb
app/cho/data_dictionary/fields_controller.rb
app/cho/transaction/operations/shared/save.rb
spec/cho/collection/with_members_spec.rb
spec/valkyrie/change_set_persister_spec.rb

During our upgrade to Valkyrie 1.2.0, we discovered that we were using persisters incorrectly and passing change sets to them, instead of resources. In order to follow the prescribed practices, we're fixing it so that we send resources to our persisters instead of change sets.

Don't pass change sets to persisters

---

spec/cho/transaction/operations/file/characterize_spec.rb
spec/fixtures/fits_output.xml

Testing FITS locally should not have to rely on what version you have
installed. The characterization test now checks the xml output from FITS
with an xpath query.

Update FITS testing to be version-agnostic

---

app/cho/transaction/operations/import/extract.rb
app/cho/transaction/operations/import/zip.rb
app/cho/transaction/shared/save_with_change_set.rb
app/cho/work/import/csv_dry_run.rb
spec/cho/transaction/operations/import/extract_spec.rb
spec/cho/transaction/shared/save_with_change_set_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/support/import_factory/zip.rb

Process zip uploads in the GUI as we do when we run csv import: import the zip files as bags and create the file sets and files contained within them.
Connected to #553

Import zip files as bags when uploaded via the GUI

---

app/cho/collection/common_fields.rb
app/cho/data_dictionary/field.rb
app/cho/schema/metadata.rb
app/cho/work/file.rb
app/cho/work/file_set.rb
app/cho/work/submission.rb
app/cho/work/type.rb
spec/cho/collection/with_members_spec.rb
spec/cho/shared/common_queries_spec.rb
spec/valkyrie/find_model_spec.rb
spec/valkyrie/find_using_spec.rb

The id attribute is now included in Valkyrie::Resource so we don't need to define it in our resources. This gets rid of some warnings during the test suite.

Removing id attribute declaration

---

app/cho/import/work.rb
spec/cho/import/bag_spec.rb
spec/cho/import/work_spec.rb

The order of the file sets present in the work was affecting certain
test runs. This refactors the tests to check for the different file set
ids as well as their representative without having to rely on the order
in which they are returned.
Additionally, the order of error messages in the bag is no longer being
tested.

Don't rely on array orders when testing bags

---

app/blacklight/search_builder.rb
spec/blacklight/catalog_spec.rb

Fixes: #498 
Product owner requested that files and file sets are not returned in the listing of search results.
Updates the blacklight search builder to filter on Collections and Works.

Remove Files and Filesets from the Search Results

---

app/cho/import/file.rb
spec/cho/import/file_set_spec.rb
spec/cho/import/file_spec.rb
spec/cho/import/work_spec.rb

The identifier for an import work needs to include the work id as well
as its other numeric indicators. This is so it will map to the
identifier that is used in csv import.
Connected to #582

Import file identifier should include the work id

---

app/cho/work/submission_change_set.rb
spec/cho/work/submissions/change_set_spec.rb

Using Reform's virtual property features, we can make import_work
defined as a property on the change set only, and not pass it on to the
resource.
Connected to #582

Make import_work a virtual property

---

app/cho/transaction/operations/import/work.rb
app/cho/work/file_set_change_set.rb
app/cho/work/import/csv_dry_run.rb
app/cho/work/import/csv_reader.rb
app/cho/work/import/file_set_hash_validator.rb
app/cho/work/import/work_hash_validator.rb
app/cho/work/submission_change_set.rb
spec/cho/work/file_set_change_set_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/import/csv_controller_spec.rb
spec/cho/work/import/csv_reader_spec.rb
spec/cho/work/import/file_set_hash_validator_spec.rb
spec/cho/work/submissions/change_set_spec.rb

When importing works that contain file sets, read the metadata for each
file set from the provided csv. We can determine if a row of the csv is
a file set or work and then pass this information on to the transaction
which will apply the metadata when creating the file set.
Connected to #582 
1. File sets' member ids are no longer required. This means that we can create a file set without any files, which seems reasonable. In this case, we want to validate the file set's metadata as it's coming our of the csv, so it won't have any files attached to it yet.
2. CsvReader is more domain-specific. Because a line in a csv could either be a work or a file set, it seemed to make sense for the CsvReader to make that distinction. The downside is that the reader now needs to know more specific …

Apply CSV metadata to FileSet

---

spec/cho/work/import/create_spec.rb

Renames a duplicate test fixture which was breaking the master build.

Rename duplicate batch id in conflicting test

---

app/cho/import/file.rb
spec/cho/import/file_set_spec.rb
spec/cho/import/file_spec.rb
spec/cho/import/work_spec.rb

Files in bags will have ids with multiple underscore-delimited segments. In order to determine the use type and file set id, the parent directory name can be used to remove the first N number of segments and the remaining segments can be used to determine file set id and use type.
Fixes #655

Fixing Import::File

---

app/assets/stylesheets/cho.scss
app/assets/stylesheets/cho/footer.scss
app/views/shared/_footer.html.erb
config/initializers/git_revision.rb
spec/views/footer.html.erb_spec.rb

Adds footer partial and style sheet and a module for the display of the commits in Git. Adds a test for the inclusion of the revision info in the footer.
Fixes #648

Adds revision Info to the Footer

---

app/cho/data_dictionary/field.rb
app/cho/data_dictionary/fields_for_change_set.rb
app/cho/data_dictionary/fields_for_object.rb
app/cho/work/import/csv_dry_run.rb
app/views/work/import/csv/_dry_run_result.html.erb
spec/cho/work/import/csv_dry_run_spec.rb
spec/cho/work/import/file_set_hash_validator_spec.rb

Adds methods to DataDictionary::Field to return the specific Valkyrie::Type for a given field when it is assigned to either a resource or a change set.
Connected to #443
* adds `change_set_property_type` and `resource_property_type` methods to DataDictionary::Field
* fixes a latent bug in CsvDryRun where the change sets were returning singular values instead of multiple ones

Define resource and change set property types for fields

---

app/cho/data_dictionary/fields_for_change_set.rb
app/cho/schema/none.rb
app/cho/work/file_set_change_set.rb
app/cho/work/submission_change_set.rb
app/cho/work/with_form_fields.rb
spec/cho/schema/none_spec.rb
spec/cho/transaction/operations/shared/validate_spec.rb
spec/cho/work/file_set_change_set_spec.rb
spec/cho/work/submissions/change_set_spec.rb

When a field is required, the Schema::MetadataField object should determine what to do when the field is missing. This allows fields to be required for different kinds of the same objects, such as submissions, and allows a field to be required by different classes.
Connected to #443

Schema should control determination of required fields

---

app/cho/transaction/operations/import/work.rb
spec/cho/work/import/create_spec.rb

The file set's metadata was not being correctly linked from the hash to the import file set. Once it was correctly linked, the metadata needed to be synced from the change set to the resource.
Connected to #582
There was still a bug with importing file set metadata via csv.

Sync file set metadata to resource

---

app/cho/transaction/operations/import/extract.rb
app/cho/transaction/rejection.rb
spec/cho/transaction/operations/import/extract_spec.rb
spec/cho/transaction/rejection_spec.rb
spec/cho/work/import/create_spec.rb

Return a Transaction::Rejection object so we can add failure errors that are interpretable by the presenter.
Connected to #618

Use a Rejection to capture failures from transactions

---

spec/cho/import/bag_spec.rb
spec/cho/import/file_spec.rb
spec/cho/import/work_spec.rb
spec/support/clean_tmp.rb
spec/support/import_factory/bag.rb
spec/support/import_factory/file.rb
spec/support/import_factory/work.rb

The tmp directory was getting a little crowded with all the sample bags. This also cleans up our tmp directory before rspec is run.

Import factory directory for building test fixtures

---

LICENSE.md

Adds Apache 2.0 license to the repository.
We are required to have licenses on all our repos. Typically, Penn State uses MIT licenses, but because this is derivative work from Samvera, we're using Apache 2.0.

Adding Apache 2.0 license

---

app/blacklight/search_builder.rb
spec/blacklight/catalog_spec.rb

Returns the parent Work when searching for the title of a File. This code was copied from ScholarSphere and adapted for CHO.
Fixes #122 
Product owner and stakeholders would like to keep search results refined but still return works when searching finer grained details.

Return the work when searching for a file name

---

app/blacklight/solr_document.rb
app/views/catalog/_file_sets.html.erb
app/views/catalog/_show_work_fileset.html.erb
app/views/catalog/show.html.erb
spec/cho/work/file_set/show_spec.rb
spec/factories/file_sets.rb

Utilizing solr document to access the link for the file set and hook into the default Blacklight show page.
Updates the file set link in the work show page to link to file set show p[age and starts a test for the file set show page.
Fixes #63 
Stakeholders would like to be able to see, and in the future, edit file sets.

Default show page for file sets

---

app/cho/transaction/operations/file/characterize.rb
app/cho/transaction/operations/file/create.rb
app/cho/transaction/operations/file/create_temp_file.rb
app/cho/transaction/operations/file/save.rb
app/cho/transaction/operations/file_set/extract_text.rb
app/cho/transaction/operations/import/validate.rb
app/cho/transaction/operations/import/work.rb
app/cho/transaction/operations/import/zip.rb
spec/cho/transaction/operations/file/characterize_spec.rb
spec/cho/transaction/operations/file/create_spec.rb
spec/cho/transaction/operations/file/create_temp_file_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/file_set/extract_text_spec.rb
spec/cho/transaction/operations/import/validate_spec.rb
spec/cho/transaction/operations/import/work_spec.rb

Updates transaction operations to use the Rejection class for errors including their corresponding tests.
Fixes #643

Update transactions to use rejection class

---

Gemfile
Gemfile.lock
app/cho/data_dictionary/field.rb
app/cho/data_dictionary/with_index_type.rb
app/cho/indexing/dates.rb
app/cho/metrics/collection.rb
app/cho/validation/factory.rb
app/cho/validation/methods.rb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv
config/data_dictionary/data_dictionary_test.csv
config/data_dictionary/schema_fields.yml
config/initializers/valkyrie.rb
spec/blacklight/solr_document_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/data_dictionary/with_index_type_spec.rb
spec/cho/indexing/dates_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/cho/validation/factory_spec.rb
spec/cho/validation/methods_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/support/matchers/blacklight.rb

Field types designated as "date" can now be validated as EDTF dates, as well as indexed as dates in Solr. The default is to index imprecise dates to midnight of the first day of their earliest range.
Valkyrie will store the value of the date as a string, according to how it was initially entered by the user; however, it will be cast to a Time object if it can be. EDTF dates will not be cast to Date objects, and will only come back as the same strings as they were entered.
Connected to #267

Support for dates, including EDTF date types

---

.rubocop.yml
app/blacklight/catalog_controller.rb
app/cho/data_dictionary/field.rb
config/data_dictionary/data_dictionary_test.csv
spec/blacklight/catalog_spec.rb
spec/factories/works.rb

Adds a faceted field based on its index type in the data dictionary. This doesn't address custom facets for collections and work types. Collections could be made to work with this setup, but we'd need to explore using transformations, which haven't been implemented yet.
Connected to #459

Add facet fields based on the data dictionary

---

app/cho/import/work.rb

When reading bags off the disk, the order of file sets and any nested
works is dependent on the order in which they are read off of the file
system. In some cases, Travis was reading these in a different order
than our local machines. To make this explicit, the files and
directories within a bag are sorted on their identifiers, in the case of
works, or their filenames, in the case of file sets.

Explicit sorting by name when reading from the file system

---

.gitignore
app/blacklight/catalog_controller.rb
app/blacklight/show_presenter.rb
app/blacklight/thumbnail_presenter.rb
app/cho/metrics/repository.rb
app/views/catalog/_show_main_content.html.erb
app/views/catalog/_thumbnail.html.erb
app/views/catalog/show.html.erb
config/application.yml
config/deploy.rb
config/initializers/valkyrie.rb
spec/blacklight/show_presenter_spec.rb
spec/cho/work/file_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/valkyrie/change_set_persister_spec.rb

Using Blacklight's features and overriding them where needed, we're displaying thumbnails on search results and show views for works and file sets.
Connected to #740 
* creates custom Blacklight presenters
* moves files storage to the public directory for easier linking
* indexes a thumbnail's path in the work and file set
* identifies representative file sets for works

Display thumbnails in search results and show views

---

app/cho/controlled_vocabulary/base.rb
app/cho/controlled_vocabulary/factory.rb
app/cho/controlled_vocabulary/none.rb
app/cho/schema/input_field.rb
app/views/shared/_form_fields.html.erb
app/views/shared/input_partials/_string.html.erb
app/views/shared/input_partials/_text.html.erb
app/views/shared/input_partials/_valkyrie_id.html.erb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/controlled_vocabulary/base_spec.rb
spec/cho/controlled_vocabulary/none_spec.rb
spec/cho/schema/input_field_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

Delegates different field types to partials, placing the logic for
determining options, display names, and controlled vocabulary lists on
the input field.
The partials allow more complex rendering which will be needed in
forthcoming field types, such as the creator which has multiple inputs.
Connected to #730

Refactor InputField

---

config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/schema/metadata_core_fields_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/cho/work/submissions/change_set_spec.rb

The specs needed to change in many places because the core field contents are checked in many places

Adding creator as a core field

---

app/cho/metrics/work.rb
spec/cho/metrics/work_spec.rb

When generating files for benchmarking works, the content was always binary regardless of what kind of file was created. In cases when the file is a text-type of file, we need to use text content.
This generates the same amount of random data per file, but uses text if the file is a text mime-type; otherwise, it's random bytes.
Fixes #765

Generate correct type of random content

---

app/cho/batch/delete_controller.rb
app/cho/batch/delete_presenter.rb
app/cho/work/submission.rb
app/valkyrie/change_set_persister.rb
app/views/batch/confirm.html.erb
config/locales/cho.yml
spec/cho/batch/delete_controller_spec.rb
spec/cho/batch/delete_presenter_spec.rb
spec/cho/batch/select_spec.rb
spec/cho/work/submissions/delete_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/valkyrie/change_set_persister_spec.rb

Presents a confirmation message with a list of contained items when deleting works or collections and includes the counts of those items in the success message.
Fixes #509

Delete contained works from collections

---

app/blacklight/solr_document.rb
app/views/catalog/_show_work_fileset.html.erb
app/views/catalog/show.html.erb
spec/cho/work/file_set/show_spec.rb
spec/factories/file_sets.rb

Gets work title using inverse references and a query service via the Solr document because it is "easier" this way than trying to create a two directional relationship between the fileset and the work. Checks to see if there is a thumbnail since we are using the same show partial for filesets and works and displays one or two columns.
Connected to #633

Fileset Show Page - Part 1

---

.rubocop.yml
app/blacklight/catalog_controller.rb
app/cho/agent/resource.rb
app/cho/data_dictionary/with_index_type.rb
app/cho/indexing/creator.rb
app/cho/indexing/linked_fields.rb
app/cho/metrics/collection.rb
app/cho/schema/input_field.rb
app/views/shared/input_partials/_creator.html.erb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_test.csv
config/initializers/valkyrie.rb
config/locales/cho.yml
spec/blacklight/catalog_spec.rb
spec/cho/controlled_vocabulary/creators_spec.rb
spec/cho/data_dictionary/with_index_type_spec.rb
spec/cho/indexing/linked_fields_spec.rb
spec/cho/schema/input_field_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/factories/works.rb
spec/support/mock_rdf.rb
spec/support/shared/views.rb
spec/views/shared/_creator.html.erb_spec.rb
spec/views/work_submissions/new.html.erb_spec.rb

Enables adding a creator to a work or collection via the GUI.
Connected to #733 
* includes a MockRDF class for mocking large RDF vocabularies across the entire test suite

Form for adding creators to works or collections

---

.solr_wrapper.yml
config/solr_wrapper_test.yml

Updating solr version so it works with java 11
The error you get is that solr_wrapper never starts up and just times out with the newer java and solr 7.1.0

Changing to solr 7.4.0

---

spec/blacklight/catalog_spec.rb
spec/cho/batch/delete_presenter_spec.rb
spec/cho/batch/select_spec.rb
spec/cho/work/submissions/delete_spec.rb
spec/factories/works.rb
spec/valkyrie/change_set_persister_spec.rb

By only extracting text from sample file when needed for explicit testing, we can reduce test suite times. Two traits are available to a work, the typical one will add a file but not extract any text or perform other post-processing. The other trait will validate the file as well as extract text.
In the future, this will also comprise characterization and derivative creation as well.

Improve test suite speed by limiting text extraction

---

spec/support/csv_factory/generic.rb
spec/support/csv_factory/update.rb

Calling .unlink on tempfiles was causing some failures because sometimes the file will have been deleted by another process. Using rm_f ignores any errors, and ensures the file is deleted.

Prefer rm_f over unlink

---

Gemfile
Gemfile.lock
app/cho/transaction/operations/file/create_temp_file.rb

Use released versions of gems, as opposed to tracking master branches, and remove an unneeded puts in the transaction code.

Cleaning dependencies and tests

---

app/cho/transaction/shared/save_with_change_set.rb
app/cho/validation/edtf_date.rb
spec/cho/validation/edtf_date_spec.rb

Fixes two minor problems:
* allow non-EDTF dates that can be parsed as actual dates
* allow works without files
These allow CHO to function with existing works. Prior to this change, any edits to existing works would not work.
Connected to #782

Bug fixes for system usability

---

app/cho/import/bag.rb
app/cho/import/file.rb
app/cho/import/file_set.rb
app/cho/import/work.rb
app/cho/metrics/repository.rb
app/cho/work/file_set.rb
spec/cho/import/bag_spec.rb
spec/cho/import/file_set_spec.rb
spec/cho/import/file_spec.rb
spec/cho/import/work_spec.rb
spec/cho/work/file_set_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/submissions/new_spec.rb

This makes some changes to the bag validation based on some feedback from @ntallman using some _real world_ zip files for import.
Additionally, files in the ingest directory are no longer cleaned out automatically with the `reset` task. This was causing problems with existing zip files that need to be retained for continued use.
Related to #750 
* dates are no longer required in batch ids but will still be parsed and returned if they're in the right format
* access files are required for representative file sets instead of service files
* file sets with preservation files are no longer considered "representative" file sets
* the ingest directory will only be cleaned out in the test environment

Changes to bag requirements

---

Gemfile
Gemfile.lock

Update Bootstrap to 4.3.1

---

app/cho/csv/controller_behavior.rb
app/cho/csv/dry_run_behavior.rb
app/cho/transaction/operations/import/csv.rb
app/cho/transaction/operations/import/extract.rb
spec/cho/agent/import/csv_dry_run_spec.rb
spec/cho/transaction/operations/import/csv_spec.rb

Deletes extracted bags from the extraction directory after they are
validated or imported. Refactors the existing csv import process into a transaction for better
maintainability and error handling.
Connected to #829

Delete extracted bags after validation and import

---

Gemfile.lock

Update to the latest new_relic_rpm gem.
Enables continued access to the New Relic suite of performance monitoring tools.

Update to the latest new_relic_rpm gem

---

app/cho/validation/base.rb
app/cho/validation/creator.rb
app/cho/validation/factory.rb
config/locales/cho.yml
spec/cho/validation/creator_spec.rb

Checks the validity of the hashes used for creators, including the presence of the agent and role keys, as well as verifying that their respective resources exist.
This work will be used in validating the agents submitted via csv for work import.
Connected to #736

Validate creator input

---

spec/cho/work/import/create_spec.rb
spec/support/csv_factory/agent_update.rb
spec/support/csv_factory/generic.rb
spec/support/csv_factory/update.rb
spec/support/metadata_factory.rb

In the process of working on #736, our generated csv files were not allowing commas or other punctuation within a field. This was blocking the ability to split first and last names using a comma.
Using the `to_csv` method will can correctly escape quotes, commas, and other punctuation that we want to keep within a field. Also creates a MetadataFactory class to generate random fields with punctuation to ensure a csv will be correctly imported.
Connected to #736

Ensure csv values are correctly escaped

---

app/blacklight/catalog_search_behavior.rb
app/blacklight/document/csv.rb
app/blacklight/solr_document.rb
app/cho/collection/with_members.rb
app/cho/import/work.rb
app/cho/transaction/operations/file/save.rb
app/cho/transaction/operations/import/work.rb
app/cho/work/submission.rb
app/cho/work/submission_change_set.rb
app/valkyrie/change_set_persister.rb
spec/blacklight/solr_document_spec.rb
spec/cho/metrics/work_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/import/work_spec.rb
spec/cho/work/file_set/delete_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/factories/file_sets.rb
spec/valkyrie/change_set_persister_spec.rb

Parent resources were not updated when their child members were deleted. This fixes that by doing a larger scale change and unifying all the membership methods between Valkyrie resources.
All memberships, whether many-to-one or one-to-many, can be found using the `member_ids` method. This makes the process of delete contained resources and updating their containing resources much easier.
Connected to #638
* `file_set_ids` is changed to `member_ids`
* collection membership can also be expressed in ids with `member_ids`
* ChangeSetPersister#delete updates containing/parent resources when their members are deleted

ChangeSetPersister#delete should update parent resources

---

app/cho/agent/resource.rb
app/cho/shared/csv_parsing.rb
app/cho/work/import/work_hash_validator.rb
spec/blacklight/solr_document_spec.rb
spec/cho/csv/reader_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/import/csv_reader_spec.rb
spec/factories/agent.rb

Takes a correctly-formatted agent/role combination in the csv creator field and parses it so that it will be correctly linked in the application. Errors are reported in the dry run if the agent or role does not exist.
Connected to #736

Parse agents and roles in csv files

---

app/cho/agent/csv_presenter.rb
app/cho/agent/import/csv_dry_run.rb
app/cho/agent/resources_controller.rb
app/views/agent/import/csv/_dry_run_result.html.erb
spec/cho/agent/controller_spec.rb
spec/cho/agent/import/csv_dry_run_spec.rb

There were a number of issues with the Agent process.  Editing an agent blew up (see image below) csv files created by excel included the BOM character which caused the id label not to be parsed correctly, the labels on export were titleized, and the formatting was off on the display.
Connected to #843 
Connected to #820
* Added BOM encoding
* Fixed bug with agent vs agent_resource in the params
* removed the titleize from the export
Import screen formatting
Before parameter change:
After Parameter change:

Fixing bugs with agent import

---

app/cho/work/submission_indexer.rb
spec/cho/work/submissions/new_spec.rb

If the representative file set lacks a thumbnail, or otherwise doesn't have a representative file set at all, choose the first file set that has a thumbnail and use that for display purposes.
Connected to #827

Assume a representative thumbnail if there isn't one

---

.rubocop_todo.yml
app/cho/work/import/work_hash_validator.rb
spec/cho/work/import/work_hash_validator_spec.rb

This was requested to make the import process more foolproof.
Connected to #656 
* allow work_type to be case insensitive

allowing work type to have any case

---

.rubocop_todo.yml
lib/tasks/bag.rake

rake cho:bag:create_from_path[/Users/cam156/Downloads/thumb2_2019-03-13]
cam156@L5-PW3-153-233[~/Downloads]> find thumb2_2019-03-13/*
thumb2_2019-03-13/thumb2
thumb2_2019-03-13/thumb2/thumb2_00001_01_thumb.png
thumb2_2019-03-13/thumb2/thumb2_00001_01_preservation.tif
For testing purposes it is nice to have the ability to quickly create bags from various test files.
The requirements for the bag and the zipped file are a bit ambiguos and it is hard to create them on a mac without the .DS_Store files.  This rake task will create a bag from a directory of files in the correct structure.

Adding a rake task to create a bag that is able to be imported

---

spec/cho/repository/downloads_controller_spec.rb
spec/factories/file_sets.rb
spec/support/file_factory.rb

Corrects a problem with the file fixtures used in file sets. The use types were not being correctly set.
Additionally, refactors the FileFactory code in conjunction with the file set factory bot.
Thanks to @cam156 for catching this!

Use correct use types in file fixtures

---

app/cho/work/import/work_hash_validator.rb
app/cho/work/submission_change_set.rb
spec/cho/work/import/work_hash_validator_spec.rb

Adding a validation to not allow work type to change
Connected to #817
* Add a validation to disallow work type from changing
* Allow work_type to be modified by the hash validator, so the error message will be produced

disallow a changing work type in the validation

---

app/cho/csv/hash_validator.rb
config/locales/cho.yml
spec/cho/csv/hash_validator_spec.rb

Fixing a bug when the id does not match any item on update works.

Adding a title so the display does not blow up

---

app/cho/work/import/csv_dry_run.rb
app/cho/work/import/csv_dry_run_results_presenter.rb
app/cho/work/import/file_set_hash_validator.rb
app/cho/work/import/with_hash_creators.rb
app/cho/work/import/work_hash_validator.rb
app/views/work/import/csv/_dry_run_result.html.erb
app/views/work/import/csv/dry_run_results.html.erb
config/locales/cho.yml
spec/cho/work/import/create_spec.rb
spec/cho/work/import/update_spec.rb
spec/support/import_factory/zip.rb

Corrects errors and inconsistencies when creating or updated metadata in file sets via the csv import process.
Connected to #686

CSV metadata for works and file sets

---

app/cho/indexing/creator.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/import/update_spec.rb

Corrects a bug with creators that have no role specified in their csv file.
Connected to #736

Allow creators with no roles to index correctly

---

app/views/work/submissions/_form.html.erb
spec/cho/work/submissions/edit_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

For works that have been batch imported and have file sets attached, there is no meaningful reason to be able to edit the file.
Connected to #845 
* Remove file upload from work submissions form, if the resource has been persisted

Remove file upload from work edit form

---

app/blacklight/solr_document.rb
app/cho/work/submission.rb
app/cho/work/submission_indexer.rb
spec/blacklight/solr_document_spec.rb
spec/cho/work/import/update_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/factories/file_sets.rb

Distinguishes between preservation file sets and representative file sets for the purposes of display in the work landing page.
Connected to #482

Default SolrDocument#file_sets to preservation file sets

---

app/blacklight/solr_document.rb
app/cho/work/submission.rb
app/cho/work/submission_indexer.rb
app/views/catalog/_download_representatives.html.erb
app/views/catalog/_show_header.html.erb
app/views/catalog/show.html.erb
config/locales/cho.yml
spec/blacklight/solr_document_spec.rb
spec/cho/work/submissions/show_spec.rb
spec/factories/works.rb

On the Work landing page, add dedicated buttons to download the representative access file and the full plain text. If the work has a thumbnail, these buttons are added in the left column just below the thumbnail; if the work has no thumbnail, there is no left column so the buttons are added above the work's title. The styles need a little love... it would be great if we could do a little flexbox magic and lay the buttons out vertically if there's a thumbnail, and horizontally if not. @mtribone, perhaps you and I could pair on that while @awead is out tomorrow (Thursday).
_Please note,_ this functionality works through a new field in the solr document, so you will need to rebuild your solr index to see it.
Connected to #482 
* Index representative file set id in solr
* Add new partial for …

Buttons download representative work & plain text

---

app/cho/work/file.rb
app/views/catalog/_show_work_fileset.html.erb
config/initializers/mime_types.rb
spec/cho/work/file_set/delete_spec.rb
spec/cho/work/file_spec.rb

On the File Set landing page, replace the list of file downloads with a table, which shows the filename (which itself is a link to download the file) along with the file size and the file type of each available file
Please be aware that the file size is not stored anywhere in a File's metadata at the moment, which means that we have to hit the disk for every file in this list on every page view. This could have scaling issues down the road, for instance if the files are stored in a cloud service, or just not on the same machine as the web server. I would like to see the file size stored in the database but we are splitting that out into a separate ticket.
Mike and I are going to be pairing on some UI stuff tomorrow so I'm hoping we'll take a look through this one as well.
Connected to …

Show a fileset's files as a table with type, size

---

.rubocop.yml
app/blacklight/catalog_controller.rb
app/blacklight/local_helper_behavior.rb
app/blacklight/metadata_field_presenter.rb
app/blacklight/solr_document.rb
app/cho/display_transformation/factory.rb
app/views/catalog/_show_collection_archival.html.erb
app/views/catalog/_show_collection_curated.html.erb
app/views/catalog/_show_collection_library.html.erb
app/views/shared/transformation_partials/_paragraph_heading.html.erb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv
config/data_dictionary/data_dictionary_test.csv
config/data_dictionary/schema_fields.yml
spec/blacklight/metadata_field_presenter_spec.rb
spec/blacklight/solr_document_spec.rb
spec/cho/collection/archival_collections/new_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/collection/curated_collections/new_spec.rb
spec/cho/collection/library_collections/new_spec.rb
spec/cho/display_transformation/factory_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/work/import/update_spec.rb

Creates a new kind of transformation that displays a property as a separate paragraph with a heading. This is used in conjunction with a new acknowledgments property that is available to collections.
Connected to #572 
* add heading transformation
* acknowledgments property to collections
* MetadataFieldPresenter for displaying contents of field as separate paragraphs

Paragraph-heading transformation for acknowledgments

---

app/blacklight/catalog_controller.rb
app/blacklight/local_helper_behavior.rb
app/blacklight/solr_document.rb
app/cho/display_transformation/factory.rb
app/views/shared/transformation_partials/_paragraph.html.erb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv
config/data_dictionary/data_dictionary_test.csv
config/data_dictionary/schema_fields.yml
spec/blacklight/solr_document_spec.rb
spec/cho/collection/archival_collections/new_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/collection/curated_collections/new_spec.rb
spec/cho/collection/library_collections/new_spec.rb
spec/cho/display_transformation/factory_spec.rb
spec/cho/schema/configuration_spec.rb

Creates a new kind of transformation that displays a property as one or more paragraphs. This is used with the new `narrative` property on collections that allows curators to provide text content.
Connected to #899 
* Add new `narrative` field to data dictionary (please double check I got all the options right)
* Add new display transformation partial for a paragraph type
* Narrative gets displayed above Acknowledgments (and metadata list) on Collection pages... displaying it below the Acknowledgments made it look like it was a part of that section

Paragraph transformation for curator’s textual narrative

---

app/cho/validation/character_encoding.rb
app/cho/validation/factory.rb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv
config/data_dictionary/data_dictionary_test.csv
config/locales/cho.yml
spec/cho/data_dictionary/fields_controller_spec.rb
spec/cho/schema/metadata_field_spec.rb
spec/cho/validation/character_encoding_spec.rb
spec/cho/validation/factory_spec.rb
spec/postgres/utf8_spec.rb

UTF-8 validation

---

app/valkyrie/find_using.rb
spec/valkyrie/find_using_spec.rb

Fixes bug when querying Postgres with values that have punctuation.
Connected to #885

Escape characters when querying Postgres

---

.eslintrc.json
app/javascript/form_fields/field.js
app/javascript/form_fields/field_set.js
app/javascript/packs/form_fields.js
config/webpack/loaders/eslint.js
package.json
yarn.lock

Uses the standard settings for linting JS files.
Connected to #797
I'm punting on Travis integration because we'll likely be moving to CircleCI and that has better options for building Ruby+Node apps.

Installing eslint

---

app/views/collection/archival_collections/edit.html.erb
app/views/collection/curated_collections/edit.html.erb
app/views/collection/library_collections/edit.html.erb
app/views/work/file_sets/edit.html.erb
app/views/work/submissions/edit.html.erb
config/locales/cho.yml
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/work_file_sets/edit.html.erb_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

Links to the show page should reference the catalog path, via Blacklight's solr document, and not the postgres Valkyrie object.
Connected to #478

Use polymorphic solr_document path for show links

---

Gemfile
Gemfile.lock
app/application/application_controller.rb
app/assets/javascripts/blacklight_gallery.js
app/assets/javascripts/openseadragon.js
app/assets/stylesheets/application.css
app/assets/stylesheets/blacklight_gallery.css.scss
app/assets/stylesheets/openseadragon.css
app/blacklight/catalog_controller.rb
app/blacklight/solr_document.rb

Adds the blacklight-gallery gem, but there are several things of note here
The current official release of blacklight-gallery gem does not support Blacklight 7, therefore I had to install it from the master branch of its GitHub repository. We are using and alpha version of the gem.
The masonry layout looks quite terrible and our image thumbnails are not properly cropped/resized to the columns as would be expected. I personally am hesitant to deploy this, so I will leave it up to the rest of the team to decide whether it is ready go now, or needs some UI attention before it is deployed.
On a technical note, CHO's nonstandard app folder layout caused the installation generators for both blacklight-gallery and its dependency opeanseadragon to crash. I read through their code, and manually …

Add Blacklight gallery

---

app/cho/repository/config_file.rb
app/cho/repository/configuration.rb
spec/cho/repository/config_file_spec.rb
spec/cho/repository/configuration_spec.rb

Expanding on a previous commit that verifies our server-side configuration files, this checks the permissions on any directories in the config file and raises errors if they are not readable or writable depending on the requirements.
This will help avoid problems when reading and extracting bags.

Check permissions on configured directories

---

config/deploy.rb

Makes sure the symlinks are correct under `shared/public` so that when Capistrano links to them, they exist and are pointing to the right locations.
The symlink to `public/files` will need to be removed later once #967 is completed.

Create symlinks under the public directory during deployment

---

spec/cho/work/submissions/multiple_fields_spec.rb
spec/support/webdriver_helpers.rb

With updated versions of chromedriver, clickable actions were causing WebDriverError exceptions. Simply retrying the action solves the problem.

Retry click actions

---

app/blacklight/catalog_controller.rb
app/cho/collection/change_set_behaviors.rb
app/cho/collection/common_fields.rb
app/cho/metrics/collection.rb
app/cho/work/file_set.rb
app/views/collection/base/_form.html.erb
config/locales/cho.yml
lib/tasks/ingest.rake
spec/cho/collection/archival_collections/archival_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/collection/common_fields_spec.rb
spec/cho/collection/curated_collections/curated_spec.rb
spec/cho/collection/library_collections/library_spec.rb
spec/cho/work/file_set_spec.rb
spec/cho/work/submissions/submission_spec.rb
spec/factories/archival_collections.rb
spec/factories/curated_collections.rb
spec/factories/library_collections.rb
spec/support/shared/controllers.rb
spec/support/shared/models.rb
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/archival_collections/new.html.erb_spec.rb
spec/views/curated_collections/edit.html.erb_spec.rb
spec/views/curated_collections/new.html.erb_spec.rb
spec/views/library_collections/edit.html.erb_spec.rb
spec/views/library_collections/new.html.erb_spec.rb

Access controls were already available to most of the resources in CHO, except file sets. This adds the controls to file sets, as well as as the tests for all the resources (collections, works, file sets) that ensures the access controls are working as expected.
Connected to #973 
* add access controls to file sets
* create shared spec tests for access controls
* rename visibility to access level

Add access controls to Valkyrie resources

---

app/cho/transaction/operations/file/save.rb
app/cho/transaction/operations/import/work.rb
spec/cho/transaction/operations/file/characterize_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/import/work_spec.rb
spec/support/fits_mock.rb

Adds the FITs characterization output to Files and persists it. Works for CSV imports as well as GUI uploads. 
This commit also moves the fits mocking for travis into a spec support file for easy inclusion into any spec.
Connected to #620
* operations:file:save adds fits characterization to the file if a preservation file
* operations:import:work adds fits characterizations to any preservation preservation file
* mocking fits for travis moved into its own spec support file

Add fits characterization to preservation files

---

spec/cho/transaction/operations/file/characterize_spec.rb
spec/cho/transaction/operations/file/save_spec.rb
spec/cho/transaction/operations/import/work_spec.rb
spec/support/fits_mock.rb

Because the test suite runs reeeeealy slow if you're shelling out to fits all the time, let's just mock it for everything. Including the :with_fits keyword in a test scope will cause it to actually run, which we're only using in one test for now. Fits is always mocked in Travis.

Mock all the fits

---

.rspec

Make RSpec's output a little more informative, showing the particular test that is being performed at the time. This could help with identifying errors in the test suite sooner.

Using documentation output for RSpec

---

config/deploy.rb

Override the existing install_bundler task from the capistrano-rbenv-install gem to install the version of bundler that is used in the application. This avoids issues with incompatibilities between Ruby versions and versions of the bundler gem.

Install bundler

---

app/blacklight/catalog_controller.rb
spec/blacklight/catalog_spec.rb

Updates the catalog controller to use only the core fields in the dropdown menu for the search bar.
Solves the problem of the All Fields criteria not working correctly and targets the core fields for the search. The dropdown was being populated by everything in the Data Dictionary. 
Connected to #804 
* store search field config in an array for usage later outside of the Data Dictionary loop
* adds the All Fields as the first search option
* uses the stored search array as and additional search field after the All Fields

Search Criteria are Core Fields Only 

---

app/views/catalog/_document_edit_link.html.erb
app/views/collection/archival_collections/edit.html.erb
app/views/collection/base/_form.html.erb
app/views/collection/curated_collections/edit.html.erb
app/views/collection/library_collections/edit.html.erb
app/views/shared/_form_delete.html.erb
app/views/work/submissions/_form.html.erb
app/views/work/submissions/edit.html.erb
spec/cho/collection/archival_collections/show_spec.rb
spec/cho/collection/curated_collections/show_spec.rb
spec/cho/collection/library_collections/show_spec.rb
spec/cho/work/file_set/delete_spec.rb
spec/cho/work/submissions/delete_spec.rb
spec/cho/work/submissions/edit_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/cho/work/submissions/show_spec.rb
spec/support/shared/collections.rb
spec/views/archival_collections/edit.html.erb_spec.rb
spec/views/work_submissions/edit.html.erb_spec.rb

Swaps the links for buttons on the show, edit UI elements in the forms based on accessibility feedback.
Based on accessibility testing feedback, the user though it would be better if the links were buttons. They would "jump out" a little better and be more recognizable than just links.
Connected to #868 
* swap links for buttons 
* update the tests

Change Show, Edit, Cancel Links to Buttons for Accessibility

---

app/views/work/submissions/_form.html.erb
config/locales/cho.yml

Adds a fieldset to organize the label for the file browse and upload functionality of the form for better accessibility.
During user accessibility testing, the user didn't immediately find the upload button among all of the metadata fields. Suggestion was to add a fieldset to make it more noticeable and navigable.
Connected to #867 
* Adds fieldset and legend

Adds Fieldset to Upload Button for Better Accessibility

---

app/views/shared/_footer.html.erb

Accessibility test revealed that the revision text outside of the link doesn't give the link enough context.
Connected to #902 
* link_to block for revision text and revision number

Moves revision text to inside of the link

---

app/cho/agent/change_set.rb
app/cho/agent/resource.rb
app/devise/ability.rb
app/views/agent/resources/index.html.erb
spec/cho/agent/agent_spec.rb
spec/cho/agent/change_set_spec.rb
spec/devise/ability_spec.rb

If an Agent has any members (for example, works they're listed as a creator upon), the delete link is hidden. Otherwise the delete link is visible, with a javascript "are you sure...?" confirmation.
Connected to #837 
* Add method to fetch member ids of an Agent
* Update Ability class to ensure an Agent has no members before allowing it to be deleted

Can delete Agents only if they have no members

---

app/devise/ability.rb
app/devise/user.rb
spec/devise/ability_spec.rb
spec/devise/user_spec.rb

Blanket read ability should not be given to any registered user, only read access to resources that have explicitly granted such access to a registered user.
There also does not need to be a public group. Public membership is implied for all users.
* replace public with psu as the default groups for registered users
* remove read access to any resource for authenticated users

Use registered group to govern access

---

.codeclimate.yml

Adds a local CodeClimate config file to better track which files we exclude, and other future settings for the service.

Adding a local CodeClimate config file

---

config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/collection/change_set_behaviors_spec.rb
spec/cho/data_dictionary/field_spec.rb
spec/cho/schema/configuration_spec.rb
spec/cho/schema/metadata_core_fields_spec.rb
spec/cho/schema/work_type_configuration_spec.rb
spec/cho/work/file_set_change_set_spec.rb
spec/cho/work/import/update_spec.rb
spec/cho/work/submissions/change_set_spec.rb
spec/cho/work/submissions/new_spec.rb

We need an edtf date to be part of the _core_ data dictionary fields in order to test searching on them
* copy `date_cataloged` over from dev data dictionary verbatim
* update a gazillion specs

Add an edtf date to the core fields of test data dictionary

---

app/blacklight/catalog_search_behavior.rb
spec/blacklight/catalog_spec.rb

Extracted text was previously being added to every Blacklight search, which was leading to some very unexpected results. Now, we only add extracted text to the query if "All Fields" is the selected search field.
Connected to #1005

Extracted text only added to "All Fields" search

---

app/cho/data_dictionary/field.rb
app/views/shared/input_partials/_radio_button.html.erb
config/data_dictionary/data_dictionary_development.csv
config/data_dictionary/data_dictionary_production.csv
config/data_dictionary/data_dictionary_test.csv
spec/blacklight/solr_document_spec.rb
spec/cho/collection/archival_collections/edit_spec.rb
spec/cho/collection/archival_collections/new_spec.rb
spec/cho/collection/curated_collections/edit_spec.rb
spec/cho/collection/curated_collections/new_spec.rb
spec/cho/collection/library_collections/edit_spec.rb
spec/cho/collection/library_collections/new_spec.rb
spec/cho/data_dictionary/field_spec.rb

Leverages a data dictionary field's default value on both change sets and resources. This allows us to specify a default value for access rights, as well as render the edit form with the access rights value selected in the radio button.
Connected to #477 and #1012 
* adds a field's default value to both the change set and Valkyrie::Resource
* updates the radio_button partial to display with the object's access rights value selected by the radio button

Enable default values on change sets and resources

---

app/cho/csv/importer.rb
app/cho/work/import/csv_dry_run.rb
spec/cho/work/import/csv_controller_spec.rb

Updating existing resources from a CSV failed due the lack of a bag. Bags are now ignored during the csv update process and a work's file sets are updated based on the metadata exported from the csv.
Connected to #888 
* any bag reference during a csv update is considered a "failure" and
will be ignored
* Csv::Importer now updates contained file sets for each work
We didn't need any new tests because the existing tests were already exercising this part of the code; however, I believe they were passing because the bag was always present. By forcing `bag` to be a `Dry::Monads::Result::Failure` if we're doing an update, makes `CsvDryRun` build file set hashes on the work from the csv.
There's also a bit of reliance on `file_set_hashes` in the importer since this class is also used for agents …

Update resources via CSV

---

app/assets/stylesheets/cho/blacklight.scss
app/views/agent/import/csv/create.html.erb
app/views/agent/import/csv/dry_run_results.html.erb
app/views/agent/import/csv/update.html.erb
app/views/agent/resources/index.html.erb
app/views/catalog/_document_edit_link.html.erb
app/views/catalog/show.html.erb
app/views/collection/archival_collections/edit.html.erb
app/views/collection/base/_form.html.erb
app/views/collection/curated_collections/edit.html.erb
app/views/collection/library_collections/edit.html.erb
app/views/work/file_sets/_form.html.erb
app/views/work/file_sets/edit.html.erb
app/views/work/import/csv/create.html.erb
app/views/work/import/csv/dry_run_results.html.erb
app/views/work/import/csv/update.html.erb
app/views/work/submissions/_form.html.erb
app/views/work/submissions/edit.html.erb

Updates the partials with buttons to follow a primary, secondary, tertiary pattern to unify the look and feel of the user interface.
Updating the interface to use buttons consistently based on Bootstrap. primary buttons for primary actions like create, secondary outline buttons for things like delete if on a create page, and make link buttons look like links for things like show.
Connected to #960 
* whole lotta CSS class refinement

Consistent look for buttons

---

app/valkyrie/date_time_json_value.rb
config/application.rb
spec/cho/work/submissions/multiple_fields_spec.rb
spec/valkyrie/date_time_json_value_spec.rb

Allows iso8601 dates that do not have time stamps, such as 1956-12-31, to be returned as strings and not DateTime objects. This allow for EDTF date-style processing at other points in the application.
Connected to #1035

Override Valkyrie::Persistence::Shared::JSONValueMapper::DateValue

---

app/cho/csv/controller_behavior.rb
app/cho/csv/importer.rb
app/cho/shared/valkyrie_controller_behaviors.rb
app/cho/transaction/operations/import/csv.rb
app/cho/transaction/operations/import/work.rb
spec/cho/collection/archival_collections/new_spec.rb
spec/cho/collection/curated_collections/new_spec.rb
spec/cho/collection/library_collections/new_spec.rb
spec/cho/csv/importer_spec.rb
spec/cho/work/import/create_spec.rb
spec/cho/work/submissions/new_spec.rb
spec/support/selectors.rb

Sets the current user when creating works and file sets.
Connected to #975 
* current user wasn't being applied to the change set even if it did have the method available
* current user also needed to be applied to file sets created in transactions
* current user should be passed along during csv import

Set the current user when creating works and file sets

---

app/assets/javascripts/matomo.js.erb
app/cho/repository/configuration.rb
config/application.yml

Piwik id had been hard-coded to 2. It is now configurable via application.yml
In order for this to take effect, we will need to talk to the devops folks. The following key-value should be added to application.yml in chef on the following servers
```
piwik_id: '2'
piwik_id: '5'
piwik_id: '6'
```
(Note that Figaro likes all values to be strings)
Connected to #951

piwik id is configurable by application.yml

---

app/views/catalog/_show_collection_archival.html.erb
app/views/catalog/_show_collection_library.html.erb
app/views/catalog/show.html.erb
config/locales/cho.yml
spec/cho/collection/archival_collections/show_spec.rb
spec/cho/collection/curated_collections/show_spec.rb
spec/cho/collection/library_collections/show_spec.rb
spec/cho/work/import/create_spec.rb
spec/support/shared/collections.rb

This is a small step in our Collection landing pages tickets. Still using the Blacklight partials and the search context (catalog) to display the show page. However, we have the title of the collection at the top and the description in the first column. Collection metadata goes into the second column.
Title and description are duplicated in the metadata output, but will be resolved in future work on the collection landing pages.
This paves the way for the representative image, browse button, searching the collection, etc.
Connected to #896 
* Removes the tools partial from the display to give more room for the two column layout
* Adds the collection title to an `<h1>` at the top of the page
* Grabs the description field contents and displays it under the title in the first column
* Uses …

Collection Landing Page in two Columns without Resources

---

.rubocop.yml
app/cho/collection/url_helper_behavior.rb
app/views/collection/resources/show.html.erb
config/locales/cho.yml
config/routes.rb
spec/cho/collection/archival_collections/browse_spec.rb
spec/cho/collection/resources_routing_spec.rb

Expands the nested resources controller to include a show view. This enables viewing a work within its containing collection and serves as a mechanism for browsing through paginated lists of works in a collection.
Connected to #807
* adds a route to `/archival_collections/:archival_collection_id/resources/:id`
* distinguishes between the catalog search/browse and the collection search/browse
There may be some unintended confusion the search results from a catalog search and those from a collection search. They appear to be mostly separate, however, there might be some yet-to-be-seen issues. Also, file sets still display within the context of the catalog controller and not their containing resource.

Adding a viewing context to works in collections

---

Gemfile
Gemfile.lock

Now that Valkyrie 2.0 is officially out, we can use the released gem and not the release candidate.

Update to Valkyrie 2.0 (for real this time)

---

app/cho/collection/representative_image_presenter.rb

The original code I'd written to generate a URL for the collection representative images was a little too tricky for its own good and appeared to get confused with the symlinked directory in production. This new version is dumber, which in this case should be a good thing.
Connected to #897

More robust collection image path generation

---

.eslintrc.json
app/cho/schema/input_field.rb
app/cho/validation/unique.rb
app/cho/validation/validations_controller.rb
app/javascript/controllers/fields_controller.js
app/javascript/controllers/validator.js
config/routes.rb
spec/cho/schema/input_field_spec.rb
spec/cho/validation/routing_spec.rb
spec/cho/validation/validations_controller_spec.rb
spec/cho/work/submissions/remote_validation_spec.rb

Augments the ES6 fields controller to add validation functionality with a remote validate endpoint that returns the same custom error messages, only as a json response so we can update the UI immediately when there is any invalid input.
* ValidationsController for remote validating of input
* Validator js controller querying the rails controller
* changes to Fields js controller and UI elements for selecting the content and reporting outcomes
* introduces a dependency on jQuery

Validate form input asynchronously
